// Unless explicitly stated otherwise all files in this repository are licensed
// under the MIT License.
// This product includes software developed at Guance Cloud (https://www.guance.com/).
// Copyright 2021-present Guance, Inc.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "gitlab.jiagouyun.com/cloudcare-tools/datakit/internal/kubernetes/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ClusterLoggingConfigs returns a ClusterLoggingConfigInformer.
	ClusterLoggingConfigs() ClusterLoggingConfigInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ClusterLoggingConfigs returns a ClusterLoggingConfigInformer.
func (v *version) ClusterLoggingConfigs() ClusterLoggingConfigInformer {
	return &clusterLoggingConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
