// Unless explicitly stated otherwise all files in this repository are licensed
// under the MIT License.
// This product includes software developed at Guance Cloud (https://www.guance.com/).
// Copyright 2021-present Guance, Inc.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterLoggingConfigListerExpansion allows custom methods to be added to
// ClusterLoggingConfigLister.
type ClusterLoggingConfigListerExpansion interface{}
