// Unless explicitly stated otherwise all files in this repository are licensed
// under the MIT License.
// This product includes software developed at Guance Cloud (https://www.guance.com/).
// Copyright 2021-present Guance, Inc.

package inputs

type ENVInfo struct {
	FieldName string
	// If empty, generated by prefix + FieldName. example: DisableHostTag --> ENV_INPUT_NEO4J_DISABLE_HOST_TAG
	ENVName string
	// If empty, generated by ENVName. example: DISABLE_HOST_TAG --> disable_host_tag
	ConfField string
	Type      string
	Example   string
	Default   string
	Desc      string
	DescZh    string
}
