### how to use this document
### 1: install extension, rest client, in vscode
### 2: create xxx.rest file
### 3: edit xxx.rest file u created under rest client format
### 4: send request by click "Send Request" at the top of every request item

###
@host = http://localhost:9528
@xtoken = tkn_2dc438b6693711eb8ff97aeee04b54af
@xprecision =


###
POST {{host}}/v1/write/metric HTTP/1.1
X-Token: {{xtoken}}
X-Precision: {{xprecision}}

{
  "json":"jsoncontent",
}

###
POST {{host}}/v1/write/object HTTP/1.1
X-Token: {{xtoken}}
X-Precision: {{xprecision}}

{
  "json":"jsoncontent",
}

###
POST {{host}}/v1/write/keyevent HTTP/1.1
X-Token: {{xtoken}}
X-Precision: {{xprecision}}

{
  "json":"jsoncontent",
}

###
POST {{host}}/v1/write/logging HTTP/1.1
X-Token: {{xtoken}}
X-Precision: {{xprecision}}

{
  "json":"jsoncontent",
}

###
POST {{host}}/v1/write/tracing HTTP/1.1
X-Token: {{xtoken}}
X-Precision: {{xprecision}}

{
  "json":"jsoncontent",
}

###
POST {{host}}/v1/write/rum HTTP/1.1
X-Token: {{xtoken}}
X-Precision: {{xprecision}}

{
  "json":"jsoncontent",
}

###
POST {{host}}/v1/write/security?token={{xtoken}} HTTP/1.1

test-01,category=host,host=ubt-server,level=warn,title=a\ demo message="passwd 发生了变化" 1619598040000435871

###
GET {{host}}/v1/check/token/:{{xtoken}} HTTP/1.1

###
POST {{host}}/v1/update/object" HTTP/1.1
X-Token: {{xtoken}}
X-Precision: {{xprecision}}

{
  "json":"jsoncontent",
}

###
GET  {{host}}/v1/keyconfig" HTTP/1.1

###
POST {{host}}/v1/disable/keys" HTTP/1.1
X-Token: {{xtoken}}
X-Precision: {{xprecision}}

{
  "json":"jsoncontent",
}