FROM pubrepo.guance.com/base/ubuntu:20.04 AS base
ARG TARGETARCH

ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /usr/local/datakit

RUN sed -i 's/\(archive\|security\|ports\).ubuntu.com/mirrors.aliyun.com/' /etc/apt/sources.list \
  && apt-get update \
  && apt-get --no-install-recommends install -y unzip wget curl

# download data files required by datakit
RUN wget --no-check-certificate -q -O data.tar.gz https://static.guance.com/datakit/data.tar.gz \
  && tar -xzf data.tar.gz -C /usr/local/datakit && rm -rf data.tar.gz

COPY dist/datakit_elinker-linux-${TARGETARCH}/ /usr/local/datakit/

CMD ["/usr/local/datakit/datakit", "run", "-C"]
