FROM registry.jiagouyun.com/middlewares/uniontechos-server-zy-root:v2.0 AS base
ARG TARGETARCH

RUN mkdir -p /opt/logfwd

COPY dist/datakit-linux-${TARGETARCH}/externals/logfwd /opt/logfwd

CMD ["/opt/logfwd/logfwd", "-config", "/opt/logfwd/config"]
