FROM mcr.microsoft.com/windows/servercore:ltsc2019

ARG exe="dist/datakit-windows-amd64"
ARG target="C:/Program Files/datakit/"

RUN mkdir ${target}

COPY ${exe} ${target}

# download data files required by datakit
ADD https://zhuyun-static-files-production.oss-cn-hangzhou.aliyuncs.com/datakit/data.tar.gz data.tar.gz
RUN tar -zxvf data.tar.gz -C ${target}
RUN del "data.tar.gz"

ARG dataway=""
ARG loglevel=""
ARG global_tags=""
ARG hostname=""
ARG name=""
ARG http_listen=""
ARG rum_origin_ip_header=""
ARG enable_pprof=""
ARG disable_protect_mode=""
ARG default_enabled_inputs=""
ARG enable_election=""

ENV ENV_DATAWAY=$dataway \
    ENV_LOG_LEVEL=$loglevel \
    ENV_GLOBAL_TAGS=$global_tags \
        ENV_NAME=$name \
        ENV_HTTP_LISTEN=$http_listen \
        ENV_RUM_ORIGIN_IP_HEADER=$rum_origin_ip_header \
        ENV_ENABLE_PPROF=$enable_pprof \
        ENV_DISABLE_PROTECT_MODE=$=$disable_protect_mode \
        ENV_DEFAULT_ENABLED_INPUTS=$default_enabled_inputs \
        ENV_ENABLE_ELECTION=$enable_election \
    ENV_HOSTNAME=$hostname

CMD ["C:\\Program Files\\datakit\\datakit", "--docker"]