package etcd

var (
	actionList = map[string]interface{}{
		"create":       nil,
		"set":          nil,
		"get":          nil,
		"getRecursive": nil,
	}

	collectList = map[string]interface{}{
		"process_resident_memory_bytes":                                       nil,
		"etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_count": nil,
		"etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_sum":   nil,
		"etcd_debugging_mvcc_keys_total":                                      nil,
		"etcd_server_proposals_applied_total":                                 nil,
		"go_memstats_mspan_sys_bytes":                                         nil,
		"go_memstats_heap_idle_bytes":                                         nil,
		"go_memstats_mcache_inuse_bytes":                                      nil,
		"etcd_debugging_mvcc_db_compaction_keys_total":                        nil,
		// "action create etcd_debugging_store_writes_total":                  nil,
		// "action set etcd_debugging_store_writes_total":                     nil,
		"etcd_debugging_store_writes_total":                           nil,
		"etcd_server_is_leader":                                       nil,
		"go_memstats_heap_alloc_bytes":                                nil,
		"etcd_debugging_mvcc_txn_total":                               nil,
		"etcd_debugging_mvcc_watcher_total":                           nil,
		"version":                                                     nil,
		"go_info":                                                     nil,
		"go_memstats_mspan_inuse_bytes":                               nil,
		"go_memstats_stack_sys_bytes":                                 nil,
		"process_cpu_seconds_total":                                   nil,
		"etcd_grpc_proxy_events_coalescing_total":                     nil,
		"etcd_server_proposals_committed_total":                       nil,
		"etcd_server_proposals_pending":                               nil,
		"go_memstats_heap_objects":                                    nil,
		"etcd_debugging_snap_save_marshalling_duration_seconds_count": nil, //nolint:misspell
		"etcd_debugging_snap_save_marshalling_duration_seconds_sum":   nil, //nolint:misspell
		"go_memstats_heap_inuse_bytes":                                nil,
		"process_virtual_memory_bytes":                                nil,
		"etcd_grpc_proxy_cache_keys_total":                            nil,
		"etcd_server_proposals_failed_total":                          nil,
		"go_memstats_buck_hash_sys_bytes":                             nil,
		"go_memstats_mallocs_total":                                   nil,
		"go_memstats_other_sys_bytes":                                 nil,
		"etcd_debugging_mvcc_delete_total":                            nil,
		"etcd_debugging_mvcc_watch_stream_total":                      nil,
		"etcd_disk_backend_commit_duration_seconds_count":             nil,
		"etcd_disk_backend_commit_duration_seconds_sum":               nil,
		"go_memstats_frees_total":                                     nil,
		"go_memstats_mcache_sys_bytes":                                nil,
		"go_memstats_sys_bytes":                                       nil,
		"etcd_debugging_store_watch_requests_total":                   nil,
		"etcd_debugging_store_watchers":                               nil,
		"etcd_network_client_grpc_received_bytes_total":               nil,
		"go_gc_duration_seconds_count":                                nil,
		"go_gc_duration_seconds_sum":                                  nil,
		"etcd_disk_backend_snapshot_duration_seconds_count":           nil,
		"etcd_disk_backend_snapshot_duration_seconds_sum":             nil,
		"go_memstats_gc_sys_bytes":                                    nil,
		"etcd_grpc_proxy_cache_misses_total":                          nil,
		"go_memstats_next_gc_bytes":                                   nil,
		"go_threads":                                                  nil,
		"go_memstats_heap_released_bytes":                             nil,
		"process_start_time_seconds":                                  nil,
		"etcd_debugging_mvcc_db_total_size_in_bytes":                  nil,
		"etcd_debugging_mvcc_slow_watcher_total":                      nil,
		"etcd_debugging_snap_save_total_duration_seconds_count":       nil,
		"etcd_debugging_snap_save_total_duration_seconds_sum":         nil,
		// "actiongetRecursiveetcd_debugging_store_reads_total":                  nil,
		"etcd_debugging_store_reads_total":                                       nil,
		"go_memstats_gc_cpu_fraction":                                            nil,
		"etcd_disk_wal_fsync_duration_seconds_count":                             nil,
		"etcd_disk_wal_fsync_duration_seconds_sum":                               nil,
		"etcd_grpc_proxy_cache_hits_total":                                       nil,
		"etcd_grpc_proxy_watchers_coalescing_total":                              nil,
		"go_goroutines":                                                          nil,
		"go_memstats_stack_inuse_bytes":                                          nil,
		"process_open_fds":                                                       nil,
		"etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_count": nil,
		"etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_sum":   nil,
		"etcd_debugging_mvcc_range_total":                                        nil,
		"go_memstats_alloc_bytes_total":                                          nil,
		"go_memstats_lookups_total":                                              nil,
		"etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_count":    nil,
		"etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_sum":      nil,
		"server_versionetcd_server_version":                                      nil,
		"go_memstats_alloc_bytes":                                                nil,
		"process_max_fds":                                                        nil,
		"etcd_debugging_server_lease_expired_total":                              nil,
		"etcd_server_has_leader":                                                 nil,
		"etcd_server_leader_changes_seen_total":                                  nil,
		"go_memstats_heap_sys_bytes":                                             nil,
		"etcd_network_client_grpc_sent_bytes_total":                              nil,
		"etcd_debugging_mvcc_events_total":                                       nil,
		"etcd_debugging_mvcc_pending_events_total":                               nil,
		"etcd_debugging_mvcc_put_total":                                          nil,
		"etcd_debugging_store_expires_total":                                     nil,
	}
)
