{{- if .Values.datakit.dataway_secret_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.datakit.dataway_secret_name | quote }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{ .Values.datakit.dataway_secret_key | quote }}: {{ .Values.datakit.dataway_url | b64enc | quote }}
{{- end }}