// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: pbdata.proto

package io

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=Category,proto3" json:"Category,omitempty"`
	Gz       bool   `protobuf:"varint,2,opt,name=Gz,proto3" json:"Gz,omitempty"`
	Body     []byte `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *PBData) Reset() {
	*x = PBData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBData) ProtoMessage() {}

func (x *PBData) ProtoReflect() protoreflect.Message {
	mi := &file_pbdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBData.ProtoReflect.Descriptor instead.
func (*PBData) Descriptor() ([]byte, []int) {
	return file_pbdata_proto_rawDescGZIP(), []int{0}
}

func (x *PBData) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PBData) GetGz() bool {
	if x != nil {
		return x.Gz
	}
	return false
}

func (x *PBData) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_pbdata_proto protoreflect.FileDescriptor

var file_pbdata_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x69, 0x6f, 0x22, 0x48, 0x0a, 0x06, 0x50, 0x42, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x47, 0x7a, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x47, 0x7a, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x3b, 0x69, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbdata_proto_rawDescOnce sync.Once
	file_pbdata_proto_rawDescData = file_pbdata_proto_rawDesc
)

func file_pbdata_proto_rawDescGZIP() []byte {
	file_pbdata_proto_rawDescOnce.Do(func() {
		file_pbdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbdata_proto_rawDescData)
	})
	return file_pbdata_proto_rawDescData
}

var (
	file_pbdata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
	file_pbdata_proto_goTypes  = []interface{}{
		(*PBData)(nil), // 0: io.PBData
	}
)

var file_pbdata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbdata_proto_init() }
func file_pbdata_proto_init() {
	if File_pbdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbdata_proto_goTypes,
		DependencyIndexes: file_pbdata_proto_depIdxs,
		MessageInfos:      file_pbdata_proto_msgTypes,
	}.Build()
	File_pbdata_proto = out.File
	file_pbdata_proto_rawDesc = nil
	file_pbdata_proto_goTypes = nil
	file_pbdata_proto_depIdxs = nil
}
