package memcached

import "gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs"

//nolint:lll
var memFields = map[string]interface{}{
	"accepting_conns":       &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Whether or not server is accepting conns"},
	"auth_cmds":             &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of authentication commands handled, success or failure"},
	"auth_errors":           &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of failed authentications"},
	"bytes":                 &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeIByte, Desc: "Current number of bytes used to store items"},
	"bytes_read":            &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeIByte, Desc: "Total number of bytes read by this server from network"},
	"bytes_written":         &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeIByte, Desc: "Total number of bytes sent by this server to network"},
	"cas_badval":            &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of CAS reqs for which a key was found, but the CAS value did not match"},
	"cas_hits":              &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of successful CAS reqs"},
	"cas_misses":            &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of CAS reqs against missing keys"},
	"cmd_flush":             &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Cumulative number of flush reqs"},
	"cmd_get":               &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Cumulative number of retrieval reqs"},
	"cmd_set":               &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Cumulative number of storage reqs"},
	"cmd_touch":             &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Cumulative number of touch reqs"},
	"conn_yields":           &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of times any connection yielded to another due to hitting the -R limit"},
	"connection_structures": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of connection structures allocated by the server"},
	"curr_connections":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of open connections"},
	"curr_items":            &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Current number of items stored"},
	"decr_hits":             &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of successful decr reqs"},
	"decr_misses":           &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of decr reqs against missing keys"},
	"delete_hits":           &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of deletion reqs resulting in an item being removed"},
	"delete_misses":         &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "umber of deletions reqs for missing keys"},
	"evicted_unfetched":     &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Items evicted from LRU that were never touched by get/incr/append/etc"},
	"evictions":             &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of valid items removed from cache to free memory for new items"},
	"expired_unfetched":     &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Items pulled from LRU that were never touched by get/incr/append/etc before expiring"},
	"get_hits":              &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of keys that have been requested and found present"},
	"get_misses":            &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of items that have been requested and not found"},
	"hash_bytes":            &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeIByte, Desc: "Bytes currently used by hash tables"},
	"hash_is_expanding":     &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Indicates if the hash table is being grown to a new size"},
	"hash_power_level":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Current size multiplier for hash table"},
	"incr_hits":             &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of successful incr reqs"},
	"incr_misses":           &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of incr reqs against missing keys"},
	"limit_maxbytes":        &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeIByte, Desc: "Number of bytes this server is allowed to use for storage"},
	"listen_disabled_num":   &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of times server has stopped accepting new connections (maxconns)"},
	"reclaimed":             &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of times an entry was stored using memory from an expired entry"},
	"threads":               &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of worker threads requested"},
	"total_connections":     &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Total number of connections opened since the server started running"},
	"total_items":           &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Total number of items stored since the server started"},
	"touch_hits":            &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of keys that have been touched with a new expiration time"},
	"touch_misses":          &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of items that have been touched and not found"},
	"uptime":                &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "Number of secs since the server started"},
}
