// Unless explicitly stated otherwise all files in this repository are licensed
// under the MIT License.
// This product includes software developed at Guance Cloud (https://www.guance.com/).
// Copyright 2021-present Guance, Inc.

package sqlserver

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/GuanceCloud/cliutils/point"
	"github.com/cespare/xxhash/v2"
	"github.com/hashicorp/golang-lru/v2/expirable"
	"gitlab.jiagouyun.com/cloudcare-tools/datakit/internal/datakit"
	dkio "gitlab.jiagouyun.com/cloudcare-tools/datakit/internal/io"
	"gitlab.jiagouyun.com/cloudcare-tools/datakit/internal/metrics"
	"gitlab.jiagouyun.com/cloudcare-tools/datakit/internal/plugins/inputs"
)

const (
	dbmPlanObjectName = "db_exec_plan"
)

type dbmPlanObjectMeasurement struct{}

func (*dbmPlanObjectMeasurement) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Name: dbmPlanObjectName,
		Cat:  point.Object,
		//nolint:lll
		Desc:   "SQL Server DBM plan objects. Each object represents a unique execution plan identified by server:database_instance:query_signature:query_plan_hash, containing the obfuscated plan content and encryption status.",
		DescZh: "SQL Server DBM 执行计划对象。每个对象代表一个由 server:database_instance:query_signature:query_plan_hash 唯一标识的执行计划，包含脱敏后的计划内容和加密状态。",
		Tags: map[string]interface{}{
			"name":              inputs.NewTagInfo("Object identifier generated from server:database_instance:query_signature:query_plan_hash"),
			"query_plan_hash":   inputs.NewTagInfo("The binary hash value of the query execution plan generated by SQL Server"),
			"query_hash":        inputs.NewTagInfo("The binary hash value of the query generated by SQL Server"),
			"server":            inputs.NewTagInfo("The server address (host:port)"),
			"sqlserver_host":    inputs.NewTagInfo("Host name which installed SQLServer"),
			"database_instance": inputs.NewTagInfo("SQL Server instance identifier from configured tag or SQL Server server name."),
			"database_type":     inputs.NewTagInfo("The type of the database. The value is `SQLServer`"),
			"plan_type":         inputs.NewTagInfo("The format of the plan content. The value is `XML`"),
			"query_signature":   inputs.NewTagInfo("Hash signature generated from database_name:procedure_name:query_hash to link metrics and objects"),
			"database_name":     inputs.NewTagInfo("The name of the database"),
			"schema_name":       inputs.NewTagInfo("The schema name of the stored procedure (if applicable)"),
			"procedure_name":    inputs.NewTagInfo("The name of the stored procedure in the format 'schema_name.procedure_name' (if applicable)"),
		},
		Fields: map[string]interface{}{
			"message": &inputs.FieldInfo{
				DataType: inputs.String,
				Unit:     inputs.UnknownUnit,
				Desc:     "The obfuscated/normalized execution plan content (full content)",
			},
			"is_encrypted": &inputs.FieldInfo{
				DataType: inputs.Bool,
				Type:     inputs.Bool,
				Unit:     inputs.UnknownUnit,
				Desc:     "Whether the execution plan is encrypted in the database",
			},
			"plan_handle": &inputs.FieldInfo{
				DataType: inputs.String,
				Type:     inputs.String,
				Unit:     inputs.UnknownUnit,
				Desc:     "The plan handle of the execution plan",
			},
			"statement_start_offset": &inputs.FieldInfo{
				DataType: inputs.Int,
				Type:     inputs.Gauge,
				Unit:     inputs.NCount,
				Desc:     "The start offset of the statement in the execution plan",
			},
			"statement_end_offset": &inputs.FieldInfo{
				DataType: inputs.Int,
				Type:     inputs.Gauge,
				Unit:     inputs.NCount,
				Desc:     "The end offset of the statement in the execution plan",
			},
		},
	}
}

// buildAndFeedDatabasePlanObjects builds and feeds database_plan DBO objects.
func (ipt *Input) buildAndFeedDatabasePlanObjects(rowsWithPlans []*statementRowWithPlan, ptsTime time.Time) []*point.Point {
	if len(rowsWithPlans) == 0 {
		return nil
	}

	opts := append(point.DefaultObjectOptions(), point.WithTime(ptsTime))
	var pts []*point.Point

	for _, row := range rowsWithPlans {
		// Tags - name is query_hash:query_plan_hash
		planName := generatePlanCacheKey(row.querySignature, row.queryPlanHash)
		objectName := fmt.Sprintf("%s-%s", ipt.Object.name, planName)
		if ipt.databaseInstance != "" {
			objectName = fmt.Sprintf("%s-%s-%s", ipt.Object.name, ipt.databaseInstance, planName)
		}

		kvs := ipt.getKVs()

		kvs = kvs.AddTag("name", objectName)
		kvs = kvs.AddTag("query_signature", row.querySignature)
		kvs = kvs.AddTag("query_plan_hash", row.queryPlanHash)
		kvs = kvs.AddTag("query_hash", row.queryHash)
		kvs = kvs.AddTag("server", ipt.Object.name)
		kvs = kvs.AddTag("sqlserver_host", row.sqlserverHost)
		kvs = kvs.AddTag("database_type", "SQLServer")
		kvs = kvs.AddTag("plan_type", "XML")
		kvs = kvs.AddTag("database_name", row.databaseName)
		if row.schemaName != "" {
			kvs = kvs.AddTag("schema_name", row.schemaName)
		}
		if row.procedureName != "" {
			kvs = kvs.AddTag("procedure_name", row.procedureName)
		}

		// Fields
		// message contains the obfuscated plan content (empty if encrypted or error)
		kvs = kvs.Set("message", row.planObfuscated)
		kvs = kvs.Set("is_encrypted", row.isPlanEncrypted)
		kvs = kvs.Set("plan_handle", row.planHandle)
		kvs = kvs.Set("statement_start_offset", row.statementStartOffset)
		kvs = kvs.Set("statement_end_offset", row.statementEndOffset)

		pt := point.NewPoint(dbmPlanObjectName, kvs, opts...)
		pts = append(pts, pt)

		// Add to reported cache after successfully building the point
		if ipt.dbmPlanObjectCache != nil {
			ipt.dbmPlanObjectCache.Add(planName, struct{}{})
		}
	}
	return pts
}

// statementRowWithPlan stores statement row with plan information.
type statementRowWithPlan struct {
	*dbmStatementRow
	planObfuscated  string
	isPlanEncrypted bool
}

// collectDbmPlans collects execution plans from statements results and feeds database_plan DBO objects.
func (ipt *Input) collectDbmPlans(ctx context.Context, statementRows []*dbmStatementRow, ptsTime time.Time) {
	if len(statementRows) == 0 {
		return
	}

	// Initialize plan object cache if not already initialized
	if ipt.dbmPlanObjectCache == nil {
		planTTL := dbmPlanCacheTTL.Duration // default TTL: 1 hour
		if ipt.Dbm.Metric.PlanCacheTTL.Duration > 0 {
			planTTL = ipt.Dbm.Metric.PlanCacheTTL.Duration
		}
		ipt.dbmPlanObjectCache = expirable.NewLRU[string, struct{}](
			10000,
			nil,
			planTTL,
		)
	}

	start := time.Now()
	// Collect plans for statement rows
	rowsWithPlans := ipt.collectPlansForStatements(ctx, statementRows, start)
	if len(rowsWithPlans) == 0 {
		return
	}
	l.Debugf("collected %d plans, time taken: %s", len(rowsWithPlans), time.Since(start))

	// Build and feed database_plan DBO objects
	pts := ipt.buildAndFeedDatabasePlanObjects(rowsWithPlans, ptsTime)
	if len(pts) > 0 {
		if err := ipt.feeder.Feed(point.Object, pts,
			dkio.WithCollectCost(time.Since(start)),
			dkio.WithElection(ipt.Election),
			dkio.WithSource(dbmFeedName),
		); err != nil {
			ipt.feeder.FeedLastError(err.Error(),
				metrics.WithLastErrorInput(inputName),
				metrics.WithLastErrorCategory(point.Object),
			)
			l.Errorf("feed database_plan DBO failed: %s", err.Error())
		}
	}
}

// executionPlan represents an execution plan loaded from SQL Server.
type executionPlan struct {
	text      sql.NullString
	encrypted bool
}

// loadExecutionPlan loads execution plan from SQL Server for a specific statement.
func (ipt *Input) loadExecutionPlan(ctx context.Context, planHandle string, statementStartOffset, statementEndOffset int64) (*executionPlan, error) {
	if planHandle == "" {
		return nil, fmt.Errorf("empty plan handle")
	}
	rows, err := ipt.db.QueryContext(ctx, dbmPlanLookupQuery, planHandle, statementStartOffset, statementEndOffset)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
			l.Errorf("failed to close rows for plan handle: %s: %v", planHandle, err)
		}
	}()

	if !rows.Next() {
		return nil, fmt.Errorf("no plan found for plan handle: %s", planHandle)
	}

	result := &executionPlan{}

	if err := rows.Scan(&result.text, &result.encrypted); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return result, nil
}

// processPlan processes the execution plan and parses it for analysis.
func processPlan(plan string, isEncrypted bool) (string, error) {
	if isEncrypted {
		return plan, nil
	}
	if plan == "" {
		return "", nil
	}

	// Obfuscate XML plan
	obfuscateStart := time.Now()
	obfuscatedPlan, err := obfuscateXMLPlan(plan)
	dbmObfuscateDuration.WithLabelValues("plan", "xml").Observe(time.Since(obfuscateStart).Seconds())
	if err != nil {
		l.Warnf("failed to obfuscate plan: %v", err)

		// If obfuscation fails, use the original plan
		return plan, nil
	}

	return obfuscatedPlan, nil
}

// collectPlansForStatements collects execution plans for statement rows.
func (ipt *Input) collectPlansForStatements(ctx context.Context, statementRows []*dbmStatementRow, startTime time.Time) []*statementRowWithPlan {
	var resultRows []*statementRowWithPlan

	// Get max runtime configuration
	maxRunTime := ipt.Dbm.Metric.MaxRunTime
	if maxRunTime <= 0 {
		maxRunTime = 30 // Default to 30 seconds if not configured
	}
	maxRunTimeDuration := time.Duration(maxRunTime) * time.Second

	for i, row := range statementRows {
		select {
		case <-ctx.Done():
			l.Info("context done, collect plans for statements exit")
			return resultRows

		case <-datakit.Exit.Wait():
			ipt.exit()
			l.Info("datakit exit, collect plans for statements exit")
			return nil

		case <-ipt.semStop.Wait():
			ipt.exit()
			l.Info("sqlserver return, collect plans for statements exit")
			return nil

		default:
		}

		// Check if plan collection time exceeded max runtime (every 5 iterations)
		if i > 0 && i%5 == 0 {
			elapsed := time.Since(startTime)
			if elapsed > maxRunTimeDuration {
				l.Warnf("plan collection time (%s) exceeded max_run_time (%ds), stopping plan collection", elapsed, maxRunTime)
				return resultRows
			}
		}

		// Look up execution plan using plan_handle
		if row.planHandle == "" {
			l.Warnf("plan handle is empty, query_hash: %s,query_plan_hash: %s", row.queryHash, row.queryPlanHash)
			continue
		}

		// Check cache before querying to avoid unnecessary queries
		planKey := generatePlanCacheKey(row.querySignature, row.queryPlanHash)
		if ipt.dbmPlanObjectCache != nil {
			if _, ok := ipt.dbmPlanObjectCache.Get(planKey); ok {
				continue
			}
		}
		planStart := time.Now()
		plan, err := ipt.loadExecutionPlan(ctx, row.planHandle, row.statementStartOffset, row.statementEndOffset)
		dbmSQLQueryDuration.WithLabelValues("plan", "query").Observe(time.Since(planStart).Seconds())
		if err != nil {
			l.Warnf("failed to load execution plan for plan handle: %s: %v", row.planHandle, err)
			continue
		}

		obfuscatedText, _ := processPlan(plan.text.String, plan.encrypted)

		rowWithPlan := &statementRowWithPlan{
			dbmStatementRow: row,
			planObfuscated:  obfuscatedText,
			isPlanEncrypted: plan.encrypted,
		}

		resultRows = append(resultRows, rowWithPlan)
	}

	return resultRows
}

// generatePlanCacheKey generates a unique signature for a execution plan.
func generatePlanCacheKey(querySignature, queryPlanHash string) string {
	h := xxhash.New()
	_, _ = h.WriteString(querySignature)
	_, _ = h.WriteString(":")
	_, _ = h.WriteString(queryPlanHash)

	return fmt.Sprintf("%016x", h.Sum64())
}
