// Unless explicitly stated otherwise all files in this repository are licensed
// under the MIT License.
// This product includes software developed at Guance Cloud (https://www.guance.com/).
// Copyright 2021-present Guance, Inc.

package sqlserver

import (
	"time"

	"github.com/GuanceCloud/cliutils/point"
	"github.com/hashicorp/golang-lru/v2/expirable"
	dkio "gitlab.jiagouyun.com/cloudcare-tools/datakit/internal/io"
	"gitlab.jiagouyun.com/cloudcare-tools/datakit/internal/metrics"
	"gitlab.jiagouyun.com/cloudcare-tools/datakit/internal/plugins/inputs"

	"github.com/DataDog/datadog-agent/pkg/obfuscate"
)

const (
	dbmQueryObjectName = "db_query"
)

type dbmQueryObjectMeasurement struct{}

func (*dbmQueryObjectMeasurement) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Name: dbmQueryObjectName,
		Cat:  point.Object,
		//nolint:lll
		Desc:   "SQL Server DBM query objects. Each object represents a unique SQL query identified by query_signature, containing the obfuscated SQL text and encryption status.",
		DescZh: "SQL Server DBM SQL 文本对象。每个对象代表一个由 query_signature 唯一标识的 SQL 查询，包含脱敏后的 SQL 文本和加密状态。",
		Tags: map[string]interface{}{
			"query_signature": inputs.NewTagInfo("Hash signature generated from database_name:procedure_name:query_hash to link metrics and objects"),
			"query_hash":      inputs.NewTagInfo("The binary hash value of the query generated by SQL Server"),
			"server":          inputs.NewTagInfo("The server address (host:port)"),
			"sqlserver_host":  inputs.NewTagInfo("Host name which installed SQLServer"),
			"database_type":   inputs.NewTagInfo("The type of the database. The value is `SQLServer`"),
			"database_name":   inputs.NewTagInfo("The name of the database"),
			"schema_name":     inputs.NewTagInfo("The schema name of the stored procedure (if applicable)"),
			"procedure_name":  inputs.NewTagInfo("The name of the stored procedure in the format 'schema_name.procedure_name' (if applicable)"),
		},
		Fields: map[string]interface{}{
			"message": &inputs.FieldInfo{
				DataType: inputs.String,
				Unit:     inputs.UnknownUnit,
				Desc:     "The obfuscated/normalized SQL text (full text)",
			},
			"is_encrypted": &inputs.FieldInfo{
				DataType: inputs.Bool,
				Type:     inputs.Bool,
				Unit:     inputs.UnknownUnit,
				Desc:     "Whether the SQL text is encrypted in the database",
			},
		},
	}
}

func (ipt *Input) collectDbmQueries(statementRows []*dbmStatementRow, ptsTime time.Time) {
	if len(statementRows) == 0 {
		return
	}

	// Initialize query object cache if not already initialized
	if ipt.dbmQueryObjectCache == nil {
		ipt.dbmQueryObjectCache = expirable.NewLRU[string, struct{}](
			100000,
			nil,
			24*time.Hour,
		)
	}

	start := time.Now()

	opts := append(point.DefaultObjectOptions(), point.WithTime(ptsTime))
	var pts []*point.Point

	obfuscator := obfuscate.NewObfuscator(obfuscate.Config{
		SQL: obfuscate.SQLConfig{
			DBMS: obfuscate.DBMSSQLServer,
		},
	})
	for _, row := range statementRows {
		if row.querySignature == "" {
			continue
		}
		// Check cache to avoid duplicate reporting
		if ipt.dbmQueryObjectCache != nil {
			if _, ok := ipt.dbmQueryObjectCache.Get(row.querySignature); ok {
				continue
			}
		}

		kvs := ipt.getKVs()

		kvs = kvs.AddTag("name", row.querySignature)
		kvs = kvs.AddTag("query_signature", row.querySignature)
		kvs = kvs.AddTag("query_hash", row.queryHash)
		kvs = kvs.AddTag("server", ipt.Object.name)
		kvs = kvs.AddTag("sqlserver_host", row.sqlserverHost)
		kvs = kvs.AddTag("database_name", row.databaseName)
		if row.schemaName != "" {
			kvs = kvs.AddTag("schema_name", row.schemaName)
		}
		if row.procedureName != "" {
			kvs = kvs.AddTag("procedure_name", row.procedureName)
		}
		kvs = kvs.AddTag("database_type", "SQLServer")

		// Fields
		obfuscatedText := row.statementText
		// Obfuscate statement text if not already done
		if row.statementText != "" && !row.isEncrypted {
			obfResult, err := obfuscator.ObfuscateSQLString(row.statementText)
			if err != nil {
				l.Warnf("failed to obfuscate SQL for query_hash %s: %v", row.queryHash, err)
			} else {
				obfuscatedText = obfResult.Query
			}
		}

		kvs = kvs.Set("message", obfuscatedText)
		kvs = kvs.Set("is_encrypted", row.isEncrypted)

		pt := point.NewPoint(dbmQueryObjectName, kvs, opts...)
		pts = append(pts, pt)

		// Add to reported cache after successfully building the point
		if ipt.dbmQueryObjectCache != nil {
			ipt.dbmQueryObjectCache.Add(row.querySignature, struct{}{})
		}
	}

	if len(pts) > 0 {
		if err := ipt.feeder.Feed(point.Object, pts,
			dkio.WithCollectCost(time.Since(start)),
			dkio.WithElection(ipt.Election),
			dkio.WithSource(dbmFeedName),
		); err != nil {
			ipt.feeder.FeedLastError(err.Error(),
				metrics.WithLastErrorInput(inputName),
				metrics.WithLastErrorCategory(point.Object),
			)
			l.Errorf("feed dbm query DBO failed: %s", err.Error())
		}
	}
}
