
#------------------------------------   W A R N   -------------------------------------
# This file generated by Datakit. Do not edit.
#--------------------------------------------------------------------------------------

add_pattern("log_date", "%{YEAR}-%{MONTHNUM}-%{MONTHDAY}%{SPACE}%{HOUR}:%{MINUTE}:%{SECOND}")
add_pattern("status", "(ERROR|FATAL|WARNING|INFO)")
# default
grok(_, "%{log_date:time}%{SPACE}\\[%{status:status}\\]\\s+%{GREEDYDATA:msg}")
default_time(time)
