// Unless explicitly stated otherwise all files in this repository are licensed
// under the MIT License.
// This product includes software developed at Guance Cloud (https://www.guance.com/).
// Copyright 2021-present Guance, Inc.

package ingestioncanary

import (
	"crypto/rand"
	"encoding/hex"
	"strconv"
	"time"

	"github.com/GuanceCloud/cliutils/point"
)

const SyntheticMessage = "synthetic freshness probe, generated by collector ingestion_canary - do not process"

func (c *Canary) Metric(ts time.Time, round int64, tags map[string]string) *point.Point {
	opts := append(point.DefaultMetricOptions(), point.WithTime(ts))

	kvs := point.NewKVs(map[string]interface{}{
		"round": round,
	})

	if c.TestType != "" {
		kvs = kvs.AddTag("test_type", c.TestType)
	}

	for k, v := range tags {
		kvs = kvs.AddTag(k, v)
	}

	return point.NewPoint(c.Name, kvs, opts...)
}

func (c *Canary) Logging(ts time.Time, round int64, tags map[string]string) *point.Point {
	opts := append(point.DefaultLoggingOptions(), point.WithTime(ts))

	kvs := point.NewKVs(map[string]interface{}{
		"round":   round,
		"message": SyntheticMessage,
	})

	if c.TestType != "" {
		kvs = kvs.AddTag("test_type", c.TestType)
	}

	for k, v := range tags {
		kvs = kvs.AddTag(k, v)
	}

	return point.NewPoint(c.Name, kvs, opts...)
}

func (c *Canary) Tracing(ts time.Time, round int64, tags map[string]string) *point.Point {
	opts := append(point.CommonLoggingOptions(), point.WithTime(ts))

	kvs := point.NewKVs(map[string]interface{}{
		"trace_id":  GenerateID(16),
		"span_id":   GenerateID(8),
		"parent_id": "0",
		"resource":  c.Name,
		"status":    "ok",
		"start":     ts.UnixMicro(),
		"duration":  0,
		"round":     round,
	})

	kvs = kvs.AddTag("span_type", "entry")
	kvs = kvs.AddTag("source", c.Name)
	kvs = kvs.AddTag("service", c.Name)

	if c.TestType != "" {
		kvs = kvs.AddTag("test_type", c.TestType)
	}

	for k, v := range tags {
		kvs = kvs.AddTag(k, v)
	}

	return point.NewPoint(c.Name, kvs, opts...)
}

func GenerateID(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		// fallback to timestamp
		return strconv.FormatInt(time.Now().UnixNano(), 16)
	}
	return hex.EncodeToString(b)
}
