FROM pubrepo.guance.com/base/ubuntu:18.04 AS base
ARG TARGETARCH
ARG DIST_DIR

RUN mkdir -p /opt/logfwd

COPY ${DIST_DIR}/datakit-linux-${TARGETARCH}/externals/logfwd /opt/logfwd

CMD ["/opt/logfwd/logfwd", "-config", "/opt/logfwd/config"]
