FROM ubuntu:20.04

ARG TARGETARCH

RUN export DEBIAN_FRONTEND=noninteractive \
  && sed -i 's/\(archive\|security\|ports\).ubuntu.com/mirrors.aliyun.com/' /etc/apt/sources.list \
  && apt-get update && apt-get install -y make curl tree tzdata gcc
