FROM pubrepo.guance.com/base/ubuntu:22.04 AS base
ARG TARGETARCH
ARG DIST_DIR
ARG LIGHTPANDA_VERSION=0.3.6
ARG LIGHTPANDA_SHA256_AMD64=e438c0ad44e0f6916c14cf13beb003512c60438d8fd200738d2e596e73f652d6
ARG LIGHTPANDA_SHA256_ARM64=29c059cd0755a195350cc79dbcf7ee9580fd575ec3eaa31db755dbada417e616
ARG CC_HTTP_PROXY=

ENV DEBIAN_FRONTEND=noninteractive
ENV LIGHTPANDA_EXECUTABLE_PATH=/usr/local/bin/lightpanda

RUN addgroup --gid 10001 datakit \
  && adduser --disabled-password --gecos "" --uid 10001 --gid 10001 datakit \
  && usermod -aG datakit root

RUN mkdir -p /usr/local/datakit \
  && mkdir -p /usr/local/datakit/conf.d \
  && mkdir -p /usr/local/datakit/cache \
  && mkdir -p /usr/local/datakit/data \
  && mkdir -p /usr/local/datakit/pipeline \
  && mkdir -p /usr/local/datakit/externals \
  && mkdir -p /usr/local/datakit/recorder \
  && mkdir -p /opt/oracle

RUN sed -i 's/\(archive\|security\|ports\).ubuntu.com/mirrors.aliyun.com/' /etc/apt/sources.list \
  && apt-get update \
  && apt-get --no-install-recommends install -y lsb-release gpg libaio-dev libaio1 unzip wget curl ca-certificates python3 python3-pip libxml2 alien vim libsystemd-dev \
  && pip3 install requests kubernetes esdk-obs-python boto3 -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

RUN \
  case "$TARGETARCH" in \
  amd64) lightpanda_arch=x86_64; lightpanda_sha256="$LIGHTPANDA_SHA256_AMD64" ;; \
  arm64) lightpanda_arch=aarch64; lightpanda_sha256="$LIGHTPANDA_SHA256_ARM64" ;; \
  *) echo "unsupported TARGETARCH for lightpanda: $TARGETARCH" >&2; exit 1 ;; \
  esac \
  && if [ -n "$CC_HTTP_PROXY" ]; then \
    export http_proxy="$CC_HTTP_PROXY" https_proxy="$CC_HTTP_PROXY" HTTP_PROXY="$CC_HTTP_PROXY" HTTPS_PROXY="$CC_HTTP_PROXY"; \
  fi \
  && curl -fL --retry 5 --retry-delay 2 --retry-all-errors --connect-timeout 10 --max-time 300 \
    "https://github.com/lightpanda-io/browser/releases/download/${LIGHTPANDA_VERSION}/lightpanda-${lightpanda_arch}-linux" \
    -o /usr/local/bin/lightpanda \
  && echo "${lightpanda_sha256}  /usr/local/bin/lightpanda" | sha256sum -c - \
  && chmod 0755 /usr/local/bin/lightpanda \
  && /usr/local/bin/lightpanda version

# download 3rd party libraries
RUN \
  case "$TARGETARCH" in \
  amd64) \
  wget -q https://static.guance.com/otn_software/instantclient/instantclient-basiclite-linux.x64-21.10.0.0.0dbru.zip \
  -O /usr/local/datakit/externals/instantclient-basiclite-linux.zip \
  && unzip /usr/local/datakit/externals/instantclient-basiclite-linux.zip -d /opt/oracle \
  && mv /opt/oracle/instantclient_21_10 /opt/oracle/instantclient \
  && rm /usr/local/datakit/externals/instantclient-basiclite-linux.zip; \
  wget -q https://static.guance.com/otn_software/db2/linuxx64_odbc_cli.tar.gz \
  -O /usr/local/datakit/externals/linuxx64_odbc_cli.tar.gz \
  && mkdir /opt/ibm \
  && tar zxf /usr/local/datakit/externals/linuxx64_odbc_cli.tar.gz -C /opt/ibm \
  && rm /usr/local/datakit/externals/linuxx64_odbc_cli.tar.gz; \
  wget -q https://static.guance.com/oceanbase/x86/libobclient-2.1.4.1-20230510140123.el7.alios7.x86_64.rpm \
  -O /usr/local/datakit/externals/libobclient-2.1.4.1-20230510140123.el7.alios7.x86_64.rpm \
  && alien -i /usr/local/datakit/externals/libobclient-2.1.4.1-20230510140123.el7.alios7.x86_64.rpm \
  && rm /usr/local/datakit/externals/libobclient-2.1.4.1-20230510140123.el7.alios7.x86_64.rpm; \
  wget -q https://static.guance.com/oceanbase/x86/obci-2.0.6.odpi.go-20230510112726.el7.alios7.x86_64.rpm \
  -O /usr/local/datakit/externals/obci-2.0.6.odpi.go-20230510112726.el7.alios7.x86_64.rpm \
  && alien -i /usr/local/datakit/externals/obci-2.0.6.odpi.go-20230510112726.el7.alios7.x86_64.rpm \
  && rm /usr/local/datakit/externals/obci-2.0.6.odpi.go-20230510112726.el7.alios7.x86_64.rpm; \
  ;; \
  esac;

RUN \
  case "$TARGETARCH" in \
  "arm64") \
  wget -q https://static.guance.com/otn_software/instantclient/instantclient-basiclite-linux.arm64-19.19.0.0.0dbru.zip \
  -O /usr/local/datakit/externals/instantclient-basiclite-linux.zip \
  && unzip /usr/local/datakit/externals/instantclient-basiclite-linux.zip -d /opt/oracle \
  && mv /opt/oracle/instantclient_19_19 /opt/oracle/instantclient \
  && rm /usr/local/datakit/externals/instantclient-basiclite-linux.zip; \
  wget -q https://static.guance.com/oceanbase/arm/libobclient-2.1.4.1-20230510140123.el7.alios7.aarch64.rpm \
  -O /usr/local/datakit/externals/libobclient-2.1.4.1-20230510140123.el7.alios7.aarch64.rpm \
  && alien --target=arm64 -i /usr/local/datakit/externals/libobclient-2.1.4.1-20230510140123.el7.alios7.aarch64.rpm \
  && rm /usr/local/datakit/externals/libobclient-2.1.4.1-20230510140123.el7.alios7.aarch64.rpm; \
  wget -q https://static.guance.com/oceanbase/arm/obci-2.0.6.odpi.go-20230815181729.el7.alios7.aarch64.rpm \
  -O /usr/local/datakit/externals/obci-2.0.6.odpi.go-20230815181729.el7.alios7.aarch64.rpm \
  && alien --target=arm64 -i /usr/local/datakit/externals/obci-2.0.6.odpi.go-20230815181729.el7.alios7.aarch64.rpm \
  && rm /usr/local/datakit/externals/obci-2.0.6.odpi.go-20230815181729.el7.alios7.aarch64.rpm; \
  ;; \
  esac;

# download data files required by datakit
RUN wget -q -O data.tar.gz https://static.guance.com/datakit/data.tar.gz \
  && tar -xzf data.tar.gz -C /usr/local/datakit && rm -rf data.tar.gz

COPY --chown=datakit:datakit ${DIST_DIR}/datakit-linux-${TARGETARCH}/ /usr/local/datakit/

ENV PATH /usr/local/datakit:$PATH

RUN mkdir -p /var/log/datakit \
  && chown -R datakit:datakit /var/log/datakit \
  && chmod -R 775 /var/log/datakit

RUN chown -R datakit:datakit /usr/local/datakit \
  && chown -R datakit:datakit /opt/oracle

RUN chmod -R 775 /usr/local/datakit \
  && chmod -R 775 /opt/oracle

USER root

CMD ["/usr/local/datakit/datakit", "run", "-C"]
