// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/v1/SpanWrapper.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *StringSlice) Reset() {
	*x = StringSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_SpanWrapper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringSlice) ProtoMessage() {}

func (x *StringSlice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_SpanWrapper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringSlice.ProtoReflect.Descriptor instead.
func (*StringSlice) Descriptor() ([]byte, []int) {
	return file_proto_v1_SpanWrapper_proto_rawDescGZIP(), []int{0}
}

func (x *StringSlice) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type PSpanWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta        map[string]*StringSlice `protobuf:"bytes,1,rep,name=Meta,proto3" json:"Meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SpanMessage *PSpanMessage           `protobuf:"bytes,2,opt,name=SpanMessage,proto3" json:"SpanMessage,omitempty"`
}

func (x *PSpanWrapper) Reset() {
	*x = PSpanWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_SpanWrapper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PSpanWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSpanWrapper) ProtoMessage() {}

func (x *PSpanWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_SpanWrapper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSpanWrapper.ProtoReflect.Descriptor instead.
func (*PSpanWrapper) Descriptor() ([]byte, []int) {
	return file_proto_v1_SpanWrapper_proto_rawDescGZIP(), []int{1}
}

func (x *PSpanWrapper) GetMeta() map[string]*StringSlice {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PSpanWrapper) GetSpanMessage() *PSpanMessage {
	if x != nil {
		return x.SpanMessage
	}
	return nil
}

var File_proto_v1_SpanWrapper_proto protoreflect.FileDescriptor

var file_proto_v1_SpanWrapper_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x53, 0x70, 0x61, 0x6e, 0x57,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31,
	0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x53, 0x70, 0x61, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x53,
	0x6c, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xbc, 0x01, 0x0a,
	0x0c, 0x50, 0x53, 0x70, 0x61, 0x6e, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x2e, 0x0a,
	0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x53, 0x70, 0x61, 0x6e, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x32, 0x0a,
	0x0b, 0x53, 0x70, 0x61, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x53, 0x70, 0x61, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x53, 0x70, 0x61, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x48, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x6c, 0x69, 0x63, 0x65,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x87, 0x01, 0x0a, 0x21,
	0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x61, 0x76, 0x65, 0x72, 0x63, 0x6f, 0x72, 0x70, 0x2e, 0x70, 0x69,
	0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x42, 0x10, 0x53, 0x70, 0x61, 0x6e, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6a, 0x69, 0x61, 0x67,
	0x6f, 0x75, 0x79, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x63,
	0x61, 0x72, 0x65, 0x2d, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x69,
	0x74, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73,
	0x2f, 0x70, 0x69, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x64, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_SpanWrapper_proto_rawDescOnce sync.Once
	file_proto_v1_SpanWrapper_proto_rawDescData = file_proto_v1_SpanWrapper_proto_rawDesc
)

func file_proto_v1_SpanWrapper_proto_rawDescGZIP() []byte {
	file_proto_v1_SpanWrapper_proto_rawDescOnce.Do(func() {
		file_proto_v1_SpanWrapper_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_SpanWrapper_proto_rawDescData)
	})
	return file_proto_v1_SpanWrapper_proto_rawDescData
}

var file_proto_v1_SpanWrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_v1_SpanWrapper_proto_goTypes = []interface{}{
	(*StringSlice)(nil),  // 0: v1.StringSlice
	(*PSpanWrapper)(nil), // 1: v1.PSpanWrapper
	nil,                  // 2: v1.PSpanWrapper.MetaEntry
	(*PSpanMessage)(nil), // 3: v1.PSpanMessage
}
var file_proto_v1_SpanWrapper_proto_depIdxs = []int32{
	2, // 0: v1.PSpanWrapper.Meta:type_name -> v1.PSpanWrapper.MetaEntry
	3, // 1: v1.PSpanWrapper.SpanMessage:type_name -> v1.PSpanMessage
	0, // 2: v1.PSpanWrapper.MetaEntry.value:type_name -> v1.StringSlice
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_SpanWrapper_proto_init() }
func file_proto_v1_SpanWrapper_proto_init() {
	if File_proto_v1_SpanWrapper_proto != nil {
		return
	}
	file_proto_v1_Span_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_SpanWrapper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_SpanWrapper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PSpanWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_SpanWrapper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_SpanWrapper_proto_goTypes,
		DependencyIndexes: file_proto_v1_SpanWrapper_proto_depIdxs,
		MessageInfos:      file_proto_v1_SpanWrapper_proto_msgTypes,
	}.Build()
	File_proto_v1_SpanWrapper_proto = out.File
	file_proto_v1_SpanWrapper_proto_rawDesc = nil
	file_proto_v1_SpanWrapper_proto_goTypes = nil
	file_proto_v1_SpanWrapper_proto_depIdxs = nil
}
