// Unless explicitly stated otherwise all files in this repository are licensed
// under the MIT License.
// This product includes software developed at Guance Cloud (https://www.guance.com/).
// Copyright 2021-present Guance, Inc.

//go:build pipeline_jit && linux && (amd64 || arm64)

// Unless explicitly stated otherwise all files in this repository are licensed
// under the MIT License.
// This product includes software developed at Guance Cloud (https://www.guance.com/).
// Copyright 2021-present Guance, Inc.

package jit

import (
	"os"
	"testing"
)

func TestDecodePipelineGoUpstreamAndBoundaryCorpus(t *testing.T) {
	path := os.Getenv("PLATYPUS_JIT_RUNTIME")
	if path == "" {
		t.Fatal("requires real PLATYPUS_JIT_RUNTIME")
	}
	runner, err := NewRunner(path, "pipeline-go-1.4.3-datakit", 8)
	if err != nil {
		t.Fatal(err)
	}
	defer runner.Close()

	// First five byte sequences are the exact GBK encodings generated by
	// pipeline-go v1.4.3 fn_decoder_test.go::TestDecode.
	cases := []struct {
		name   string
		source string
		input  any
		want   any
	}{
		{"upstream-test-0", `decode(message,"gbk"); add_key(after,true)`, RawString("\xb2\xe2\xca\xd4\xd2\xbb\xcf\xc2"), "测试一下"},
		{"upstream-test-1", `decode(message,"gbk"); add_key(after,true)`, RawString("\xb2\xbb\xd6\xaa\xb5\xc0"), "不知道"},
		{"upstream-test-2", `decode(message,"gbk"); add_key(after,true)`, RawString("\xb2\xe2\xca\xd4\xd2\xbb\xcf\xc2123456"), "测试一下123456"},
		{"upstream-test-3", `decode(message,"gbk"); add_key(after,true)`, RawString("\xb9\xfe\xb9\xfe\xb9\xfe\xb9\xfe\xb9\xfe"), "哈哈哈哈哈"},
		{"upstream-test-4", `decode(message,"gbk"); add_key(after,true)`, RawString("-\xcd\xf498\xb0\xa2\xc8\xf8\xb5\xc2\xc0\xeb\xbf\xaa\xbc\xd2"), "-汪98阿萨德离开家"},
		{"gb18030-alias", `decode(message,"gb18030"); add_key(after,true)`, RawString("\xb2\xe2\xca\xd4"), "测试"},
		{"quoted-gbk-label", `decode(message,"'gbk'"); add_key(after,true)`, RawString("\xb2\xe2\xca\xd4"), "测试"},
		{"unknown-label-noop", `decode(message,"GBK"); add_key(after,true)`, RawString("\xb2\xe2"), RawString("\xb2\xe2")},
		{"utf8-label-noop", `decode(message,"utf-8"); add_key(after,true)`, "already", "already"},
		{"missing-noop", `decode(message,"gbk"); add_key(after,true)`, nil, nil},
		{"non-string-noop", `decode(message,"gbk"); add_key(after,true)`, int64(7), int64(7)},
		{"malformed-gbk-replacement", `decode(message,"gbk"); add_key(after,true)`, RawString("\x81"), "�"},
		{"utf16le-bom-is-content", `decode(message,"utf-16le"); add_key(after,true)`, RawString("\xff\xfeA\x00"), "\ufeffA"},
		{"utf16le-truncated-replacement", `decode(message,"utf-16le"); add_key(after,true)`, RawString("A"), "�"},
	}
	for _, size := range []int{1, 2, 4, 8, 10, 128} {
		t.Run("batch-"+itoa(size), func(t *testing.T) {
			for _, tc := range cases {
				check := runner.Check(tc.source)
				if check.Route != RouteJITNative || check.Capabilities.ExecutionMode != "native" {
					t.Fatalf("%s route=%+v", tc.name, check)
				}
				points := make([]Point, size)
				for i := range points {
					fields := map[string]any{"sequence": int64(i)}
					if tc.input != nil {
						fields["message"] = tc.input
					}
					points[i] = Point{Version: 1, Category: "logging", Measurement: tc.name, Fields: fields}
				}
				input, err := EncodeFlatPoints(points)
				if err != nil {
					t.Fatal(err)
				}
				batch, err := runner.Process(tc.source, input)
				if err != nil || len(batch.Records) != size {
					t.Fatalf("%s process records=%d error=%v", tc.name, len(batch.Records), err)
				}
				for i, record := range batch.Records {
					if record.Status != TerminalOK {
						t.Fatalf("%s record %d terminal=%d error=%s", tc.name, i, record.Status, record.Error)
					}
					applyHostCompatRecord(t, batch, i, &points[i])
					if got := points[i].Fields["message"]; got != tc.want {
						t.Fatalf("%s record %d message=%#v want=%#v", tc.name, i, got, tc.want)
					}
					if points[i].Fields["after"] != true || points[i].Fields["sequence"] != int64(i) {
						t.Fatalf("%s record %d lost input or continuation: %#v", tc.name, i, points[i])
					}
				}
			}
		})
	}
}

func itoa(value int) string {
	if value == 0 {
		return "0"
	}
	var digits [20]byte
	index := len(digits)
	for value > 0 {
		index--
		digits[index] = byte('0' + value%10)
		value /= 10
	}
	return string(digits[index:])
}
