// Unless explicitly stated otherwise all files in this repository are licensed
// under the MIT License.
// This product includes software developed at Guance Cloud (https://www.guance.com/).
// Copyright 2021-present Guance, Inc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: pbdata.proto

package diskcache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PBOption
type PBConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source                string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Pipeline              string   `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Blocking              bool     `protobuf:"varint,3,opt,name=blocking,proto3" json:"blocking,omitempty"`
	DisableAddStatusField bool     `protobuf:"varint,4,opt,name=disable_add_status_field,json=disableAddStatusField,proto3" json:"disable_add_status_field,omitempty"`
	IgnoreStatus          []string `protobuf:"bytes,5,rep,name=ignore_status,json=ignoreStatus,proto3" json:"ignore_status,omitempty"`
}

func (x *PBConfig) Reset() {
	*x = PBConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBConfig) ProtoMessage() {}

func (x *PBConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pbdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBConfig.ProtoReflect.Descriptor instead.
func (*PBConfig) Descriptor() ([]byte, []int) {
	return file_pbdata_proto_rawDescGZIP(), []int{0}
}

func (x *PBConfig) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PBConfig) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *PBConfig) GetBlocking() bool {
	if x != nil {
		return x.Blocking
	}
	return false
}

func (x *PBConfig) GetDisableAddStatusField() bool {
	if x != nil {
		return x.DisableAddStatusField
	}
	return false
}

func (x *PBConfig) GetIgnoreStatus() []string {
	if x != nil {
		return x.IgnoreStatus
	}
	return nil
}

// PBData
type PBData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []byte    `protobuf:"bytes,1,opt,name=points,proto3" json:"points,omitempty"`
	Config *PBConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *PBData) Reset() {
	*x = PBData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBData) ProtoMessage() {}

func (x *PBData) ProtoReflect() protoreflect.Message {
	mi := &file_pbdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBData.ProtoReflect.Descriptor instead.
func (*PBData) Descriptor() ([]byte, []int) {
	return file_pbdata_proto_rawDescGZIP(), []int{1}
}

func (x *PBData) GetPoints() []byte {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *PBData) GetConfig() *PBConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_pbdata_proto protoreflect.FileDescriptor

var file_pbdata_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x64, 0x69, 0x73, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x08, 0x50, 0x42,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x37, 0x0a, 0x18, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x4d, 0x0a, 0x06, 0x50, 0x42, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x69, 0x73, 0x6b, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x50, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x64, 0x69, 0x73, 0x6b, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbdata_proto_rawDescOnce sync.Once
	file_pbdata_proto_rawDescData = file_pbdata_proto_rawDesc
)

func file_pbdata_proto_rawDescGZIP() []byte {
	file_pbdata_proto_rawDescOnce.Do(func() {
		file_pbdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbdata_proto_rawDescData)
	})
	return file_pbdata_proto_rawDescData
}

var file_pbdata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbdata_proto_goTypes = []interface{}{
	(*PBConfig)(nil), // 0: diskcache.PBConfig
	(*PBData)(nil),   // 1: diskcache.PBData
}
var file_pbdata_proto_depIdxs = []int32{
	0, // 0: diskcache.PBData.config:type_name -> diskcache.PBConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pbdata_proto_init() }
func file_pbdata_proto_init() {
	if File_pbdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbdata_proto_goTypes,
		DependencyIndexes: file_pbdata_proto_depIdxs,
		MessageInfos:      file_pbdata_proto_msgTypes,
	}.Build()
	File_pbdata_proto = out.File
	file_pbdata_proto_rawDesc = nil
	file_pbdata_proto_goTypes = nil
	file_pbdata_proto_depIdxs = nil
}
