package clickhousev1

import (
	"time"

	"gitlab.jiagouyun.com/cloudcare-tools/datakit/io"
	"gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs"
)

type ProfileEventsMeasurement struct {
	name   string
	tags   map[string]string
	fields map[string]interface{}
	ts     time.Time
}

type MetricsMeasurement struct {
	name   string
	tags   map[string]string
	fields map[string]interface{}
	ts     time.Time
}

type AsyncMetricsMeasurement struct {
	name   string
	tags   map[string]string
	fields map[string]interface{}
	ts     time.Time
}

type StatusInfoMeasurement struct {
	name   string
	tags   map[string]string
	fields map[string]interface{}
	ts     time.Time
}

const (
	defaultDesc          = " - "
	TypeMetric           = "metric"
	metricsAsyncMetrics  = "ClickHouseAsyncMetrics"
	metricsMetrics       = "ClickHouseMetrics"
	metricsProfileEvents = "ClickHouseProfileEvents"
	metricsStatusInfo    = "ClickHouseStatusInfo"
)

func (m *ProfileEventsMeasurement) LineProto() (*io.Point, error) {
	return io.MakePoint(m.name, m.tags, m.fields, m.ts)
}

func (m *MetricsMeasurement) LineProto() (*io.Point, error) {
	return io.MakePoint(m.name, m.tags, m.fields, m.ts)
}

func (m *AsyncMetricsMeasurement) LineProto() (*io.Point, error) {
	return io.MakePoint(m.name, m.tags, m.fields, m.ts)
}

func (m *StatusInfoMeasurement) LineProto() (*io.Point, error) {
	return io.MakePoint(m.name, m.tags, m.fields, m.ts)
}

func (m *AsyncMetricsMeasurement) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Name: metricsAsyncMetrics,
		Type: TypeMetric,
		Fields: map[string]interface{}{
			"AsynchronousMetricsCalculationTimeSpent":  newGaugeFieldInfo(defaultDesc),
			"jemalloc_arenas_all_pmuzzy":               newGaugeFieldInfo(defaultDesc),
			"jemalloc_arenas_all_pactive":              newGaugeFieldInfo(defaultDesc),
			"FilesystemLogsPathUsedINodes":             newGaugeFieldInfo(defaultDesc),
			"jemalloc_background_thread_run_intervals": newGaugeFieldInfo(defaultDesc),
			"jemalloc_mapped":                          newGaugeFieldInfo(defaultDesc),
			"BlockReadTime_dm_0":                       newGaugeFieldInfo(defaultDesc),
			"jemalloc_resident":                        newGaugeFieldInfo(defaultDesc),
			"FilesystemMainPathTotalBytes":             newGaugeFieldInfo(defaultDesc),
			"jemalloc_metadata_thp":                    newGaugeFieldInfo(defaultDesc),
			"jemalloc_metadata":                        newGaugeFieldInfo(defaultDesc),
			"MySQLThreads":                             newGaugeFieldInfo(defaultDesc),
			"Jitter":                                   newGaugeFieldInfo(defaultDesc),
			"TotalRowsOfMergeTreeTables":               newGaugeFieldInfo(defaultDesc),
			"TotalBytesOfMergeTreeTables":              newGaugeFieldInfo(defaultDesc),
			"CompiledExpressionCacheCount":             newGaugeFieldInfo(defaultDesc),
			"NumberOfTables":                           newGaugeFieldInfo(defaultDesc),
			"NumberOfDatabases":                        newGaugeFieldInfo(defaultDesc),
			"ReplicasMaxAbsoluteDelay":                 newGaugeFieldInfo(defaultDesc),
			"ReplicasMaxMergesInQueue":                 newGaugeFieldInfo(defaultDesc),
			"ReplicasMaxInsertsInQueue":                newGaugeFieldInfo(defaultDesc),
			"NetworkReceiveBytes_virbr0_nic":           newGaugeFieldInfo(defaultDesc),
			"DiskAvailable_default":                    newGaugeFieldInfo(defaultDesc),
			"DiskUsed_default":                         newGaugeFieldInfo(defaultDesc),
			"FilesystemLogsPathTotalINodes":            newGaugeFieldInfo(defaultDesc),
			"FilesystemLogsPathAvailableByte":          newGaugeFieldInfo(defaultDesc),
			"FilesystemMainPathUsedINodes":             newGaugeFieldInfo(defaultDesc),
			"OSSystemTimeNormalized":                   newGaugeFieldInfo(defaultDesc),
			"FilesystemMainPathTotalINodes":            newGaugeFieldInfo(defaultDesc),
			"MemoryDataAndStack":                       newGaugeFieldInfo(defaultDesc),
			"NetworkSendErrors_virbr0_nic":             newGaugeFieldInfo(defaultDesc),
			"NetworkSendPackets_virbr0_nic":            newGaugeFieldInfo(defaultDesc),
			"PostgreSQLThreads":                        newGaugeFieldInfo(defaultDesc),
			"NetworkSendBytes_virbr0_nic":              newGaugeFieldInfo(defaultDesc),
			"InterserverThreads":                       newGaugeFieldInfo(defaultDesc),
			"ReplicasMaxQueueSize":                     newGaugeFieldInfo(defaultDesc),
			"NetworkReceiveDrop_virbr0_nic":            newGaugeFieldInfo(defaultDesc),
			"DiskUnreserved_default":                   newGaugeFieldInfo(defaultDesc),
			"NetworkReceiveErrors_virbr0_nic":          newGaugeFieldInfo(defaultDesc),
			"NetworkSendPackets_virbr0":                newGaugeFieldInfo(defaultDesc),
			"NetworkSendBytes_virbr0":                  newGaugeFieldInfo(defaultDesc),
			"NetworkReceiveBytes_virbr0":               newGaugeFieldInfo(defaultDesc),
			"NetworkSendPackets_ens33":                 newGaugeFieldInfo(defaultDesc),
			"NetworkSendBytes_ens33":                   newGaugeFieldInfo(defaultDesc),
			"OSSoftIrqTimeNormalized":                  newGaugeFieldInfo(defaultDesc),
			"NetworkReceiveErrors_ens33":               newGaugeFieldInfo(defaultDesc),
			"TCPThreads":                               newGaugeFieldInfo(defaultDesc),
			"BlockActiveTime_dm_0":                     newGaugeFieldInfo(defaultDesc),
			"BlockActiveTimePerOp_dm_1":                newGaugeFieldInfo(defaultDesc),
			"DiskTotal_default":                        newGaugeFieldInfo(defaultDesc),
			"FilesystemLogsPathUsedBytes":              newGaugeFieldInfo(defaultDesc),
			"NetworkSendErrors_virbr0":                 newGaugeFieldInfo(defaultDesc),
			"BlockQueueTime_dm_1":                      newGaugeFieldInfo(defaultDesc),
			"BlockDiscardTime_dm_1":                    newGaugeFieldInfo(defaultDesc),
			"BlockReadTime_dm_1":                       newGaugeFieldInfo(defaultDesc),
			"HTTPThreads":                              newGaugeFieldInfo(defaultDesc),
			"BlockDiscardMerges_dm_1":                  newGaugeFieldInfo(defaultDesc),
			"PrometheusThreads":                        newGaugeFieldInfo(defaultDesc),
			"NetworkReceiveDrop_ens33":                 newGaugeFieldInfo(defaultDesc),
			"OSMemoryTotal":                            newGaugeFieldInfo(defaultDesc),
			"BlockWriteMerges_dm_1":                    newGaugeFieldInfo(defaultDesc),
			"ReplicasSumQueueSize":                     newGaugeFieldInfo(defaultDesc),
			"BlockReadMerges_dm_1":                     newGaugeFieldInfo(defaultDesc),
			"BlockWriteMerges_sr0":                     newGaugeFieldInfo(defaultDesc),
			"BlockWriteBytes_sda":                      newGaugeFieldInfo(defaultDesc),
			"BlockWriteOps_dm_1":                       newGaugeFieldInfo(defaultDesc),
			"BlockInFlightOps_sr0":                     newGaugeFieldInfo(defaultDesc),
			"BlockDiscardTime_sr0":                     newGaugeFieldInfo(defaultDesc),
			"FilesystemMainPathAvailableINodes":        newGaugeFieldInfo(defaultDesc),
			"BlockReadMerges_dm_0":                     newGaugeFieldInfo(defaultDesc),
			"BlockDiscardBytes_sr0":                    newGaugeFieldInfo(defaultDesc),
			"BlockWriteBytes_sr0":                      newGaugeFieldInfo(defaultDesc),
			"ReplicasSumMergesInQueue":                 newGaugeFieldInfo(defaultDesc),
			"BlockDiscardMerges_sr0":                   newGaugeFieldInfo(defaultDesc),
			"BlockReadOps_dm_1":                        newGaugeFieldInfo(defaultDesc),
			"BlockReadMerges_sr0":                      newGaugeFieldInfo(defaultDesc),
			"jemalloc_allocated":                       newGaugeFieldInfo(defaultDesc),
			"OSSystemTime":                             newGaugeFieldInfo(defaultDesc),
			"OSProcessesBlocked":                       newGaugeFieldInfo(defaultDesc),
			"OSThreadsRunnable":                        newGaugeFieldInfo(defaultDesc),
			"OSMemoryFreePlusCached":                   newGaugeFieldInfo(defaultDesc),
			"BlockDiscardOps_sr0":                      newGaugeFieldInfo(defaultDesc),
			"BlockQueueTime_dm_0":                      newGaugeFieldInfo(defaultDesc),
			"BlockDiscardBytes_dm_1":                   newGaugeFieldInfo(defaultDesc),
			"OSGuestTimeNormalized":                    newGaugeFieldInfo(defaultDesc),
			"BlockWriteTime_dm_0":                      newGaugeFieldInfo(defaultDesc),
			"BlockQueueTime_sda":                       newGaugeFieldInfo(defaultDesc),
			"NetworkReceiveDrop_virbr0":                newGaugeFieldInfo(defaultDesc),
			"BlockReadOps_sda":                         newGaugeFieldInfo(defaultDesc),
			"jemalloc_epoch":                           newGaugeFieldInfo(defaultDesc),
			"OSProcessesRunning":                       newGaugeFieldInfo(defaultDesc),
			"BlockWriteBytes_dm_1":                     newGaugeFieldInfo(defaultDesc),
			"OSContextSwitches":                        newGaugeFieldInfo(defaultDesc),
			"BlockDiscardBytes_dm_0":                   newGaugeFieldInfo(defaultDesc),
			"jemalloc_arenas_all_dirty_purged":         newGaugeFieldInfo(defaultDesc),
			"BlockWriteBytes_dm_0":                     newGaugeFieldInfo(defaultDesc),
			"BlockReadOps_dm_0":                        newGaugeFieldInfo(defaultDesc),
			"jemalloc_background_thread_num_threads":   newGaugeFieldInfo(defaultDesc),
			"BlockDiscardOps_dm_0":                     newGaugeFieldInfo(defaultDesc),
			"BlockWriteOps_dm_0":                       newGaugeFieldInfo(defaultDesc),
			"BlockActiveTime_sda":                      newGaugeFieldInfo(defaultDesc),
			"FilesystemMainPathUsedBytes":              newGaugeFieldInfo(defaultDesc),
			"BlockWriteTime_dm_1":                      newGaugeFieldInfo(defaultDesc),
			"MMapCacheCells":                           newGaugeFieldInfo(defaultDesc),
			"NetworkReceivePackets_ens33":              newGaugeFieldInfo(defaultDesc),
			"BlockReadBytes_sda":                       newGaugeFieldInfo(defaultDesc),
			"BlockDiscardOps_sda":                      newGaugeFieldInfo(defaultDesc),
			"NetworkReceiveBytes_ens33":                newGaugeFieldInfo(defaultDesc),
			"OSStealTime":                              newGaugeFieldInfo(defaultDesc),
			"MemoryCode":                               newGaugeFieldInfo(defaultDesc),
			"BlockReadMerges_sda":                      newGaugeFieldInfo(defaultDesc),
			"BlockWriteOps_sda":                        newGaugeFieldInfo(defaultDesc),
			"OSMemorySwapCached":                       newGaugeFieldInfo(defaultDesc),
			"FilesystemLogsPathTotalBytes":             newGaugeFieldInfo(defaultDesc),
			"BlockInFlightOps_dm_0":                    newGaugeFieldInfo(defaultDesc),
			"OSGuestNiceTimeNormalized":                newGaugeFieldInfo(defaultDesc),
			"BlockDiscardOps_dm_1":                     newGaugeFieldInfo(defaultDesc),
			"OSOpenFiles":                              newGaugeFieldInfo(defaultDesc),
			"MarkCacheFiles":                           newGaugeFieldInfo(defaultDesc),
			"OSStealTimeNormalized":                    newGaugeFieldInfo(defaultDesc),
			"jemalloc_retained":                        newGaugeFieldInfo(defaultDesc),
			"BlockInFlightOps_dm_1":                    newGaugeFieldInfo(defaultDesc),
			"OSIrqTimeNormalized":                      newGaugeFieldInfo(defaultDesc),
			"MemoryVirtual":                            newGaugeFieldInfo(defaultDesc),
			"BlockDiscardTime_sda":                     newGaugeFieldInfo(defaultDesc),
			"BlockDiscardBytes_sda":                    newGaugeFieldInfo(defaultDesc),
			"jemalloc_arenas_all_pdirty":               newGaugeFieldInfo(defaultDesc),
			"OSIdleTimeNormalized":                     newGaugeFieldInfo(defaultDesc),
			"OSInterrupts":                             newGaugeFieldInfo(defaultDesc),
			"MemoryResident":                           newGaugeFieldInfo(defaultDesc),
			"BlockReadTime_sda":                        newGaugeFieldInfo(defaultDesc),
			"OSGuestNiceTimeCPU0":                      newGaugeFieldInfo(defaultDesc),
			"OSIrqTime":                                newGaugeFieldInfo(defaultDesc),
			"NetworkSendDrop_virbr0":                   newGaugeFieldInfo(defaultDesc),
			"BlockQueueTimePerOp_dm_1":                 newGaugeFieldInfo(defaultDesc),
			"jemalloc_arenas_all_muzzy_purged":         newGaugeFieldInfo(defaultDesc),
			"OSStealTimeCPU0":                          newGaugeFieldInfo(defaultDesc),
			"FilesystemLogsPathAvailableINodes":        newGaugeFieldInfo(defaultDesc),
			"BlockReadBytes_dm_0":                      newGaugeFieldInfo(defaultDesc),
			"TotalPartsOfMergeTreeTables":              newGaugeFieldInfo(defaultDesc),
			"NetworkReceivePackets_virbr0_nic":         newGaugeFieldInfo(defaultDesc),
			"BlockDiscardMerges_sda":                   newGaugeFieldInfo(defaultDesc),
			"BlockWriteOps_sr0":                        newGaugeFieldInfo(defaultDesc),
			"BlockWriteTime_sda":                       newGaugeFieldInfo(defaultDesc),
			"BlockQueueTime_sr0":                       newGaugeFieldInfo(defaultDesc),
			"BlockActiveTime_sr0":                      newGaugeFieldInfo(defaultDesc),
			"OSIOWaitTimeCPU0":                         newGaugeFieldInfo(defaultDesc),
			"NetworkReceiveErrors_virbr0":              newGaugeFieldInfo(defaultDesc),
			"NetworkSendDrop_ens33":                    newGaugeFieldInfo(defaultDesc),
			"OSSystemTimeCPU0":                         newGaugeFieldInfo(defaultDesc),
			"OSNiceTimeCPU0":                           newGaugeFieldInfo(defaultDesc),
			"jemalloc_background_thread_num_runs":      newGaugeFieldInfo(defaultDesc),
			"FilesystemMainPathAvailableBytes":         newGaugeFieldInfo(defaultDesc),
			"OSUserTimeCPU0":                           newGaugeFieldInfo(defaultDesc),
			"OSProcessesCreated":                       newGaugeFieldInfo(defaultDesc),
			"BlockWriteMerges_sda":                     newGaugeFieldInfo(defaultDesc),
			"OSNiceTime":                               newGaugeFieldInfo(defaultDesc),
			"BlockDiscardTime_dm_0":                    newGaugeFieldInfo(defaultDesc),
			"BlockActiveTime_dm_1":                     newGaugeFieldInfo(defaultDesc),
			"OSGuestTime":                              newGaugeFieldInfo(defaultDesc),
			"MarkCacheBytes":                           newGaugeFieldInfo(defaultDesc),
			"OSSoftIrqTime":                            newGaugeFieldInfo(defaultDesc),
			"BlockWriteTime_sr0":                       newGaugeFieldInfo(defaultDesc),
			"OSMemoryFreeWithoutCached":                newGaugeFieldInfo(defaultDesc),
			"BlockWriteMerges_dm_0":                    newGaugeFieldInfo(defaultDesc),
			"CompiledExpressionCacheBytes":             newGaugeFieldInfo(defaultDesc),
			"CPUFrequencyMHz_0":                        newGaugeFieldInfo(defaultDesc),
			"OSIOWaitTime":                             newGaugeFieldInfo(defaultDesc),
			"OSIdleTimeCPU0":                           newGaugeFieldInfo(defaultDesc),
			"LoadAverage15":                            newGaugeFieldInfo(defaultDesc),
			"BlockReadOps_sr0":                         newGaugeFieldInfo(defaultDesc),
			"OSMemoryCached":                           newGaugeFieldInfo(defaultDesc),
			"OSMemoryAvailable":                        newGaugeFieldInfo(defaultDesc),
			"OSUserTime":                               newGaugeFieldInfo(defaultDesc),
			"OSIrqTimeCPU0":                            newGaugeFieldInfo(defaultDesc),
			"NetworkSendErrors_ens33":                  newGaugeFieldInfo(defaultDesc),
			"OSUptime":                                 newGaugeFieldInfo(defaultDesc),
			"OSSoftIrqTimeCPU0":                        newGaugeFieldInfo(defaultDesc),
			"BlockDiscardMerges_dm_0":                  newGaugeFieldInfo(defaultDesc),
			"OSGuestTimeCPU0":                          newGaugeFieldInfo(defaultDesc),
			"ReplicasSumInsertsInQueue":                newGaugeFieldInfo(defaultDesc),
			"LoadAverage5":                             newGaugeFieldInfo(defaultDesc),
			"LoadAverage1":                             newGaugeFieldInfo(defaultDesc),
			"MaxPartCountForPartition":                 newGaugeFieldInfo(defaultDesc),
			"OSIOWaitTimeNormalized":                   newGaugeFieldInfo(defaultDesc),
			"jemalloc_active":                          newGaugeFieldInfo(defaultDesc),
			"NetworkSendDrop_virbr0_nic":               newGaugeFieldInfo(defaultDesc),
			"BlockReadTime_sr0":                        newGaugeFieldInfo(defaultDesc),
			"OSGuestNiceTime":                          newGaugeFieldInfo(defaultDesc),
			"ReplicasMaxRelativeDelay":                 newGaugeFieldInfo(defaultDesc),
			"OSIdleTime":                               newGaugeFieldInfo(defaultDesc),
			"NetworkReceivePackets_virbr0":             newGaugeFieldInfo(defaultDesc),
			"BlockReadBytes_sr0":                       newGaugeFieldInfo(defaultDesc),
			"UncompressedCacheBytes":                   newGaugeFieldInfo(defaultDesc),
			"Uptime":                                   newGaugeFieldInfo(defaultDesc),
			"OSThreadsTotal":                           newGaugeFieldInfo(defaultDesc),
			"BlockReadBytes_dm_1":                      newGaugeFieldInfo(defaultDesc),
			"MemoryShared":                             newGaugeFieldInfo(defaultDesc),
			"OSUserTimeNormalized":                     newGaugeFieldInfo(defaultDesc),
			"BlockInFlightOps_sda":                     newGaugeFieldInfo(defaultDesc),
			"UncompressedCacheCells":                   newGaugeFieldInfo(defaultDesc),
			"OSNiceTimeNormalized":                     newGaugeFieldInfo(defaultDesc),
		},
		Tags: map[string]interface{}{
			"host": inputs.NewTagInfo("host name"),
		},
	}
}

//nolint:lll
func (m *MetricsMeasurement) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Name: metricsMetrics,
		Type: TypeMetric,
		Fields: map[string]interface{}{
			"Query":                                   newGaugeFieldInfo(" Number of executing queries"),
			"Merge":                                   newGaugeFieldInfo(" Number of executing background merges"),
			"PartMutation":                            newGaugeFieldInfo(" Number of mutations (ALTER DELETE/UPDATE)"),
			"ReplicatedFetch":                         newGaugeFieldInfo(" Number of data parts being fetched from replica"),
			"ReplicatedSend":                          newGaugeFieldInfo(" Number of data parts being sent to replicas"),
			"ReplicatedChecks":                        newGaugeFieldInfo(" Number of data parts checking for consistency"),
			"BackgroundMergesAndMutationsPoolTask":    newGaugeFieldInfo(" Number of active merges and mutations in an associated background pool"),
			"BackgroundFetchesPoolTask":               newGaugeFieldInfo(" Number of active fetches in an associated background pool"),
			"BackgroundCommonPoolTask":                newGaugeFieldInfo(" Number of active tasks in an associated background pool"),
			"BackgroundMovePoolTask":                  newGaugeFieldInfo(" Number of active tasks in BackgroundProcessingPool for moves"),
			"BackgroundSchedulePoolTask":              newGaugeFieldInfo(" Number of active tasks in BackgroundSchedulePool. "),
			"BackgroundBufferFlushSchedulePoolTask":   newGaugeFieldInfo(" Number of active tasks in BackgroundBufferFlushSchedulePool. This pool is used for periodic Buffer flushes"),
			"BackgroundDistributedSchedulePoolTask":   newGaugeFieldInfo(" Number of active tasks in BackgroundDistributedSchedulePool. "),
			"BackgroundMessageBrokerSchedulePoolTask": newGaugeFieldInfo(" Number of active tasks in BackgroundProcessingPool for message streaming"),
			"CacheDictionaryUpdateQueueBatches":       newGaugeFieldInfo(" Number of 'batches' (a set of keys) in update queue in CacheDictionaries."),
			"CacheDictionaryUpdateQueueKeys":          newGaugeFieldInfo(" Exact number of keys in update queue in CacheDictionaries."),
			"DiskSpaceReservedForMerge":               newGaugeFieldInfo(" Disk space reserved for currently running background merges. It is slightly more than the total size of currently merging parts."),
			"DistributedSend":                         newGaugeFieldInfo(" Number of connections to remote servers sending data that was INSERTed into Distributed tables. Both synchronous and asynchronous mode."),
			"QueryPreempted":                          newGaugeFieldInfo(" Number of queries that are stopped and waiting due to 'priority' setting."),
			"TCPConnection":                           newGaugeFieldInfo(" Number of connections to TCP server (clients with native interface), also included server-server distributed query connections"),
			"MySQLConnection":                         newGaugeFieldInfo(" Number of client connections using MySQL protocol"),
			"HTTPConnection":                          newGaugeFieldInfo(" Number of connections to HTTP server"),
			"InterserverConnection":                   newGaugeFieldInfo(" Number of connections from other replicas to fetch parts"),
			"PostgreSQLConnection":                    newGaugeFieldInfo(" Number of client connections using PostgreSQL protocol"),
			"OpenFileForRead":                         newGaugeFieldInfo(" Number of files open for reading"),
			"OpenFileForWrite":                        newGaugeFieldInfo(" Number of files open for writing"),
			"Read":                                    newGaugeFieldInfo(" Number of read (read, pread, io_getevents, etc.) syscalls in fly"),
			"Write":                                   newGaugeFieldInfo(" Number of write (write, pwrite, io_getevents, etc.) syscalls in fly"),
			"NetworkReceive":                          newGaugeFieldInfo(" Number of threads receiving data from network. Only ClickHouse-related network interaction is included, not by 3rd party libraries."),
			"NetworkSend":                             newGaugeFieldInfo(" Number of threads sending data to network. Only ClickHouse-related network interaction is included, not by 3rd party libraries."),
			"SendScalars":                             newGaugeFieldInfo(" Number of connections that are sending data for scalars to remote servers."),
			"SendExternalTables":                      newGaugeFieldInfo(" Number of connections that are sending data for external tables to remote servers. "),
			"QueryThread":                             newGaugeFieldInfo(" Number of query processing threads"),
			"ReadonlyReplica":                         newGaugeFieldInfo(" Number of Replicated tables that are currently in readonly state due to re-initialization after ZooKeeper session loss or due to startup without ZooKeeper configured."),
			"MemoryTracking":                          newGaugeFieldInfo(" Total amount of memory (bytes) allocated by the server."),
			"EphemeralNode":                           newGaugeFieldInfo(" Number of ephemeral nodes hold in ZooKeeper."),
			"ZooKeeperSession":                        newGaugeFieldInfo(" Number of sessions (connections) to ZooKeeper."),
			"ZooKeeperWatch":                          newGaugeFieldInfo(" Number of watches (event subscriptions) in ZooKeeper."),
			"ZooKeeperRequest":                        newGaugeFieldInfo(" Number of requests to ZooKeeper in fly."),
			"DelayedInserts":                          newGaugeFieldInfo(" Number of INSERT queries that are throttled due to high number of active data parts for partition in a MergeTree table."),
			"ContextLockWait":                         newGaugeFieldInfo(" Number of threads waiting for lock in Context. This is global lock."),
			"StorageBufferRows":                       newGaugeFieldInfo(" Number of rows in buffers of Buffer tables"),
			"StorageBufferBytes":                      newGaugeFieldInfo(" Number of bytes in buffers of Buffer tables"),
			"DictCacheRequests":                       newGaugeFieldInfo(" Number of requests in fly to data sources of dictionaries of cache type."),
			"Revision Revision":                       newGaugeFieldInfo(" of the server. It is a number incremented for every release or release candidate except patch releases."),
			"VersionInteger":                          newGaugeFieldInfo(" Version of the server in a single integer number in base-1000. For example, version 11.22.33 is translated to 11022033."),
			"RWLockWaitingReaders":                    newGaugeFieldInfo(" Number of threads waiting for read on a table RWLock."),
			"RWLockWaitingWriters":                    newGaugeFieldInfo(" Number of threads waiting for write on a table RWLock."),
			"RWLockActiveReaders":                     newGaugeFieldInfo(" Number of threads holding read lock in a table RWLock."),
			"RWLockActiveWriters":                     newGaugeFieldInfo(" Number of threads holding write lock in a table RWLock."),
			"GlobalThread":                            newGaugeFieldInfo(" Number of threads in global thread pool."),
			"GlobalThreadActive":                      newGaugeFieldInfo(" Number of threads in global thread pool running a task."),
			"LocalThread":                             newGaugeFieldInfo(" Number of threads in local thread pools. The threads in local thread pools are taken from the global thread pool."),
			"LocalThreadActive":                       newGaugeFieldInfo(" Number of threads in local thread pools running a task."),
			"DistributedFilesToInsert":                newGaugeFieldInfo(" Number of pending files to process for asynchronous insertion into Distributed tables. Number of files for every shard is summed."),
			"BrokenDistributedFilesToInsert":          newGaugeFieldInfo(" Number of files for asynchronous insertion into Distributed tables that has been marked as broken."),
			"TablesToDropQueueSize":                   newGaugeFieldInfo(" Number of dropped tables, that are waiting for background data removal."),
			"MaxDDLEntryID":                           newGaugeFieldInfo(" Max processed DDL entry of DDLWorker."),
			"MaxPushedDDLEntryID":                     newGaugeFieldInfo(" Max DDL entry of DDLWorker that pushed to zookeeper."),
			"PartsTemporary":                          newGaugeFieldInfo(" The part is generating now, it is not in data_parts list."),
			"PartsPreCommitted":                       newGaugeFieldInfo(" The part is in data_parts, but not used for SELECTs."),
			"PartsCommitted":                          newGaugeFieldInfo(" Active data part, used by current and upcoming SELECTs."),
			"PartsOutdated":                           newGaugeFieldInfo(" Not active data part, but could be used by only current SELECTs, could be deleted after SELECTs finishes."),
			"PartsDeleting":                           newGaugeFieldInfo(" Not active data part with identity refcounter, it is deleting right now by a cleaner."),
			"PartsDeleteOnDestroy":                    newGaugeFieldInfo(" Part was moved to another disk and should be deleted in own destructor."),
			"PartsWide":                               newGaugeFieldInfo(" Wide parts."),
			"PartsCompact":                            newGaugeFieldInfo(" Compact parts."),
			"PartsInMemory":                           newGaugeFieldInfo(" In-memory parts."),
			"MMappedFiles":                            newGaugeFieldInfo(" Total number of mmapped files."),
			"MMappedFileBytes":                        newGaugeFieldInfo(" Sum size of mmapped file regions."),
			"AsyncDrainedConnections":                 newGaugeFieldInfo(" Number of connections drained asynchronously."),
			"ActiveAsyncDrainedConnections":           newGaugeFieldInfo(" Number of active connections drained asynchronously."),
			"SyncDrainedConnections":                  newGaugeFieldInfo(" Number of connections drained synchronously."),
			"ActiveSyncDrainedConnections":            newGaugeFieldInfo(" Number of active connections drained synchronously."),
			"AsynchronousReadWait":                    newGaugeFieldInfo(" Number of threads waiting for asynchronous read."),
		},
		Tags: map[string]interface{}{
			"host": inputs.NewTagInfo("host name"),
		},
	}
}

//nolint:lll,funlen
func (m *ProfileEventsMeasurement) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Name: metricsProfileEvents,
		Type: TypeMetric,
		Fields: map[string]interface{}{
			"ReadBufferFromFileDescriptorReadFailed ":          newCountFieldInfo(" Number of times the read (read/pread) from a file descriptor have failed."),
			"ReadBufferFromFileDescriptorReadBytes ":           newCountFieldInfo(" Number of bytes read from file descriptors. If the file is compressed, this will show the compressed data size."),
			"WriteBufferFromFileDescriptorWrite ":              newCountFieldInfo(" Number of writes (write/pwrite) to a file descriptor. Does not include sockets"),
			"WriteBufferFromFileDescriptorWriteFailed ":        newCountFieldInfo(" Number of times the write (write/pwrite) to a file descriptor have failed."),
			"WriteBufferFromFileDescriptorWriteBytes":          newCountFieldInfo(" Number of bytes written to file descriptors. If the file is compressed, this will show compressed data size."),
			"ReadCompressedBytes":                              newCountFieldInfo(" Number of bytes (the number of bytes before decompression) read from compressed sources (files, network)."),
			"CompressedReadBufferBlocks":                       newCountFieldInfo(" CompressedReadBufferBlocks Number of compressed blocks (the blocks of data that are compressed independent of each other) read from compressed sources (files, network)."),
			"CompressedReadBufferBytes":                        newCountFieldInfo(" Number of uncompressed bytes (the number of bytes after decompression) read from compressed sources (files, network)."),
			"AIOWrite":                                         newCountFieldInfo(" Number of writes with Linux or FreeBSD AIO interface"),
			"AIOWriteBytes":                                    newCountFieldInfo(" Number of bytes written with Linux or FreeBSD AIO interface"),
			"AIORead":                                          newCountFieldInfo(" Number of reads with Linux or FreeBSD AIO interface"),
			"AIOReadBytes":                                     newCountFieldInfo(" Number of bytes read with Linux or FreeBSD AIO interface"),
			"Query":                                            newCountFieldInfo(" Number of queries to be interpreted and potentially executed."),
			"SelectQuery":                                      newCountFieldInfo(" Same as Query, but only for SELECT queries."),
			"InsertQuery":                                      newCountFieldInfo(" Same as Query, but only for INSERT queries"),
			"FailedQuery":                                      newCountFieldInfo(" Number of failed queries."),
			"FailedSelectQuery":                                newCountFieldInfo(" Same as FailedQuery, but only for SELECT queries"),
			"FailedInsertQuery":                                newCountFieldInfo(" Same as FailedQuery, but only for INSERT queries"),
			"QueryTimeMicroseconds":                            newCountFieldInfo(" Total time of all queries."),
			"SelectQueryTimeMicroseconds":                      newCountFieldInfo(" Total time of SELECT queries."),
			"InsertQueryTimeMicroseconds":                      newCountFieldInfo(" Total time of INSERT queries."),
			"FileOpen ":                                        newCountFieldInfo(" Number of files opened"),
			"Seek ":                                            newCountFieldInfo(" Number of times the 'lseek' function was called."),
			"ReadBufferFromFileDescriptorRead":                 newCountFieldInfo(" Number of reads (read/pread) from a file descriptor. Does not include sockets."),
			"StorageBufferLayerLockReadersWaitMilliseconds":    newCountFieldInfo(" Time for waiting for Buffer layer during reading"),
			"StorageBufferLayerLockWritersWaitMilliseconds":    newCountFieldInfo(" Time for waiting free Buffer layer to write to (can be used to tune Buffer layers)"),
			"DiskReadElapsedMicroseconds":                      newCountFieldInfo(" Total time spent waiting for read syscall. This include reads from page cache."),
			"DiskWriteElapsedMicroseconds":                     newCountFieldInfo(" Total time spent waiting for write syscall. This include writes to page cache."),
			"NetworkReceiveElapsedMicroseconds":                newCountFieldInfo(" Total time spent waiting for data to receive or receiving data from network. Only ClickHouse-related network interaction is included, not by 3rd party libraries."),
			"NetworkSendElapsedMicroseconds":                   newCountFieldInfo(" Total time spent waiting for data to send to network or sending data to network. Only ClickHouse-related network interaction is included, not by 3rd party libraries.."),
			"NetworkReceiveBytes":                              newCountFieldInfo(" Total number of bytes received from network. Only ClickHouse-related network interaction is included, not by 3rd party libraries."),
			"NetworkSendBytes":                                 newCountFieldInfo(" Total number of bytes send to network. Only ClickHouse-related network interaction is included, not by 3rd party libraries."),
			"ThrottlerSleepMicroseconds":                       newCountFieldInfo(" Total time a query was sleeping to conform the 'max_network_bandwidth' setting."),
			"QueryMaskingRulesMatch":                           newCountFieldInfo(" Number of times query masking rules was successfully matched."),
			"ReplicatedPartFetches":                            newCountFieldInfo(" Number of times a data part was downloaded from replica of a ReplicatedMergeTree table."),
			"ReplicatedPartFailedFetches":                      newCountFieldInfo(" Number of times a data part was failed to download from replica of a ReplicatedMergeTree table."),
			"DistributedConnectionFailTry":                     newCountFieldInfo(" Total count when distributed connection fails with retry"),
			"ReplicatedDataLoss":                               newCountFieldInfo(" Number of times a data part that we wanted doesn't exist on any replica (even on replicas that are offline right now). "),
			"InsertedRows":                                     newCountFieldInfo(" Number of rows inserted to all tables."),
			"InsertedBytes":                                    newCountFieldInfo(" Number of bytes (uncompressed; for columns as they stored in memory) inserted to all tables."),
			"DelayedInserts":                                   newCountFieldInfo(" Number of times the INSERT of a block to a MergeTree table was throttled due to high number of active data parts for partition."),
			"RejectedInserts":                                  newCountFieldInfo(" Number of times the INSERT of a block to a MergeTree table was rejected with 'Too many parts' exception due to high number of active data parts for partition."),
			"DelayedInsertsMilliseconds":                       newCountFieldInfo(" Total number of milliseconds spent while the INSERT of a block to a MergeTree table was throttled due to high number of active data parts for partition."),
			"DistributedDelayedInserts":                        newCountFieldInfo(" Number of times the INSERT of a block to a Distributed table was throttled due to high number of pending bytes."),
			"DistributedRejectedInserts":                       newCountFieldInfo(" Number of times the INSERT of a block to a Distributed table was rejected with 'Too many bytes' exception due to high number of pending bytes."),
			"DistributedDelayedInsertsMilliseconds":            newCountFieldInfo(" Total number of milliseconds spent while the INSERT of a block to a Distributed table was throttled due to high number of pending bytes."),
			"DuplicatedInsertedBlocks":                         newCountFieldInfo(" Number of times the INSERTed block to a ReplicatedMergeTree table was deduplicated."),
			"ReplicatedPartMerges":                             newCountFieldInfo(" Number of times data parts of ReplicatedMergeTree tables were successfully merged."),
			"ReplicatedPartFetchesOfMerged":                    newCountFieldInfo(" Number of times we prefer to download already merged part from replica of ReplicatedMergeTree table instead of performing a merge ourself."),
			"DistributedConnectionFailAtAll":                   newCountFieldInfo(" Total count when distributed connection fails after all retries finished"),
			"HedgedRequestsChangeReplica":                      newCountFieldInfo(" Total count when timeout for changing replica expired in hedged requests."),
			"CompileFunction":                                  newCountFieldInfo(" Number of times a compilation of generated LLVM code (to create fused function for complex expressions) was initiated."),
			"CompiledFunctionExecute":                          newCountFieldInfo(" Number of times a compiled function was executed."),
			"CompileExpressionsMicroseconds":                   newCountFieldInfo(" Total time spent for compilation of expressions to LLVM code."),
			"CompileExpressionsBytes":                          newCountFieldInfo(" Number of bytes used for expressions compilation."),
			"SlowRead":                                         newCountFieldInfo(" Number of reads from a file that were slow. This indicate system overload. Thresholds are controlled by read_backoff_* settings."),
			"ReadBackoff":                                      newCountFieldInfo(" Number of times the number of query processing threads was lowered due to slow reads."),
			"ReplicaPartialShutdown":                           newCountFieldInfo(" How many times Replicated table has to deinitialize its state due to session expiration in ZooKeeper. "),
			"SelectedParts":                                    newCountFieldInfo(" Number of data parts selected to read from a MergeTree table."),
			"SelectedRanges":                                   newCountFieldInfo(" Number of (non-adjacent) ranges in all data parts selected to read from a MergeTree table."),
			"SelectedMarks":                                    newCountFieldInfo(" Number of marks (index granules) selected to read from a MergeTree table."),
			"SelectedRows":                                     newCountFieldInfo(" Number of rows selected from all tables."),
			"SelectedBytes":                                    newCountFieldInfo(" Number of bytes (uncompressed; for columns as they stored in memory) SELECTed from all tables."),
			"Merge":                                            newCountFieldInfo(" Number of launched background merges."),
			"MergedRows":                                       newCountFieldInfo(" Rows read for background merges. This is the number of rows before merge."),
			"MergedUncompressedBytes":                          newCountFieldInfo(" Uncompressed bytes (for columns as they stored in memory) that was read for background merges. This is the number before merge."),
			"MergesTimeMilliseconds":                           newCountFieldInfo(" Total time spent for background merges."),
			"MergeTreeDataWriterRows":                          newCountFieldInfo(" Number of rows INSERTed to MergeTree tables."),
			"MergeTreeDataWriterUncompressedBytes":             newCountFieldInfo(" Uncompressed bytes (for columns as they stored in memory) INSERTed to MergeTree tables."),
			"MergeTreeDataWriterCompressedBytes":               newCountFieldInfo(" Bytes written to filesystem for data INSERTed to MergeTree tables."),
			"MergeTreeDataWriterBlocks":                        newCountFieldInfo(" Number of blocks INSERTed to MergeTree tables. Each block forms a data part of level zero."),
			"MergeTreeDataWriterBlocksAlreadySorted":           newCountFieldInfo(" Number of blocks INSERTed to MergeTree tables that appeared to be already sorted."),
			"MergeTreeDataProjectionWriterRows":                newCountFieldInfo(" Number of rows INSERTed to MergeTree tables projection."),
			"MergeTreeDataProjectionWriterUncompressedBytes":   newCountFieldInfo(" Uncompressed bytes (for columns as they stored in memory) INSERTed to MergeTree tables projection."),
			"MergeTreeDataProjectionWriterCompressedBytes":     newCountFieldInfo(" Bytes written to filesystem for data INSERTed to MergeTree tables projection."),
			"MergeTreeDataProjectionWriterBlocks":              newCountFieldInfo(" Number of blocks INSERTed to MergeTree tables projection. Each block forms a data part of level zero."),
			"MergeTreeDataProjectionWriterBlocksAlreadySorted": newCountFieldInfo(" Number of blocks INSERTed to MergeTree tables projection that appeared to be already sorted."),
			"CannotRemoveEphemeralNode":                        newCountFieldInfo(" Number of times an error happened while trying to remove ephemeral node. "),
			"RegexpCreated":                                    newCountFieldInfo(" Compiled regular expressions. Identical regular expressions compiled just once and cached forever."),
			"ContextLock":                                      newCountFieldInfo(" Number of times the lock of Context was acquired or tried to acquire. This is global lock."),
			"DNSError":                                         newCountFieldInfo(" Total count of errors in DNS resolution"),
			"RealTimeMicroseconds":                             newCountFieldInfo(" Total (wall clock) time spent in processing (queries and other tasks) threads (not that this is a sum)."),
			"UserTimeMicroseconds":                             newCountFieldInfo(" Total time spent in processing (queries and other tasks) threads executing CPU instructions in user space. "),
			"SystemTimeMicroseconds":                           newCountFieldInfo(" Total time spent in processing (queries and other tasks) threads executing CPU instructions in OS kernel space. "),
			"OSIOWaitMicroseconds":                             newCountFieldInfo(" Total time a thread spent waiting for a result of IO operation, from the OS point of view. This is real IO that doesn't include page cache."),
			"OSCPUWaitMicroseconds":                            newCountFieldInfo(" Total time a thread was ready for execution but waiting to be scheduled by OS, from the OS point of view."),
			"OSCPUVirtualTimeMicroseconds":                     newCountFieldInfo(" CPU time spent seen by OS. Does not include involuntary waits due to virtualization."),
			"OSReadBytes":                                      newCountFieldInfo(" Number of bytes read from disks or block devices. Doesn't include bytes read from page cache. "),
			"OSWriteBytes":                                     newCountFieldInfo(" Number of bytes written to disks or block devices. Doesn't include bytes that are in page cache dirty pages. "),
			"OSReadChars":                                      newCountFieldInfo(" Number of bytes read from filesystem, including page cache."),
			"OSWriteChars":                                     newCountFieldInfo(" Number of bytes written to filesystem, including page cache."),
			"PerfCpuCycles":                                    newCountFieldInfo(" Total cycles. Be wary of what happens during CPU frequency scaling."),
			"PerfInstructions":                                 newCountFieldInfo(" Retired instructions. Be careful, these can be affected by various issues, most notably hardware interrupt counts."),
			"PerfCacheReferences":                              newCountFieldInfo(" Cache accesses. Usually this indicates Last Level Cache accesses but this may vary depending on your CPU. "),
			"PerfCacheMisses":                                  newCountFieldInfo(" Cache misses. Usually this indicates Last Level Cache misses."),
			"PerfBranchInstructions":                           newCountFieldInfo(" Retired branch instructions. Prior to Linux 2.6.35, this used the wrong event on AMD processors."),
			"PerfBranchMisses":                                 newCountFieldInfo(" Mispredicted branch instructions."),
			"PerfBusCycles":                                    newCountFieldInfo(" Bus cycles, which can be different from total cycles."),
			"PerfStalledCyclesFrontend":                        newCountFieldInfo(" Stalled cycles during issue."),
			"PerfStalledCyclesBackend":                         newCountFieldInfo(" Stalled cycles during retirement."),
			"PerfRefCpuCycles":                                 newCountFieldInfo(" Total cycles; not affected by CPU frequency scaling."),
			"PerfCpuClock":                                     newCountFieldInfo(" The CPU clock, a high-resolution per-CPU timer"),
			"PerfTaskClock":                                    newCountFieldInfo(" A clock count specific to the task that is running"),
			"PerfContextSwitches":                              newCountFieldInfo(" Number of context switches"),
			"PerfCpuMigrations":                                newCountFieldInfo(" Number of times the process has migrated to a new CPU"),
			"PerfAlignmentFaults":                              newCountFieldInfo(" Number of alignment faults. These happen when unaligned memory accesses happen; the kernel can handle these but it reduces performance."),
			"PerfEmulationFaults":                              newCountFieldInfo(" Number of emulation faults. The kernel sometimes traps on unimplemented instructions and emulates them for user space."),
			"PerfMinEnabledTime":                               newCountFieldInfo(" For all events, minimum time that an event was enabled. Used to track event multiplexing influence"),
			"PerfMinEnabledRunningTime":                        newCountFieldInfo(" Running time for event with minimum enabled time. Used to track the amount of event multiplexing"),
			"PerfDataTLBReferences":                            newCountFieldInfo(" Data TLB references"),
			"PerfDataTLBMisses":                                newCountFieldInfo(" Data TLB misses"),
			"PerfInstructionTLBReferences":                     newCountFieldInfo(" Instruction TLB references"),
			"PerfInstructionTLBMisses":                         newCountFieldInfo(" Instruction TLB misses"),
			"PerfLocalMemoryReferences":                        newCountFieldInfo(" Local NUMA node memory reads"),
			"PerfLocalMemoryMisses":                            newCountFieldInfo(" Local NUMA node memory read misses"),
			"CreatedHTTPConnections":                           newCountFieldInfo(" Total amount of created HTTP connections (counter increase every time connection is created)."),
			"CannotWriteToWriteBufferDiscard":                  newCountFieldInfo(" Number of stack traces dropped by query profiler or signal handler because pipe is full or cannot write to pipe."),
			"QueryProfilerSignalOverruns":                      newCountFieldInfo(" Number of times we drop processing of a query profiler signal due to overrun plus the number of signals that OS has not delivered due to overrun."),
			"QueryProfilerRuns":                                newCountFieldInfo(" Number of times QueryProfiler had been run."),
			"CreatedLogEntryForMerge":                          newCountFieldInfo(" Successfully created log entry to merge parts in ReplicatedMergeTree."),
			"NotCreatedLogEntryForMerge":                       newCountFieldInfo(" Log entry to merge parts in ReplicatedMergeTree is not created due to concurrent log update by another replica."),
			"CreatedLogEntryForMutation":                       newCountFieldInfo(" Successfully created log entry to mutate parts in ReplicatedMergeTree."),
			"NotCreatedLogEntryForMutation":                    newCountFieldInfo(" Log entry to mutate parts in ReplicatedMergeTree is not created due to concurrent log update by another replica."),
			"S3ReadMicroseconds":                               newCountFieldInfo(" Time of GET and HEAD requests to S3 storage."),
			"S3ReadBytes":                                      newCountFieldInfo(" Read bytes (incoming) in GET and HEAD requests to S3 storage."),
			"S3ReadRequestsCount":                              newCountFieldInfo(" Number of GET and HEAD requests to S3 storage."),
			"S3ReadRequestsErrors":                             newCountFieldInfo(" Number of non-throttling errors in GET and HEAD requests to S3 storage."),
			"S3ReadRequestsThrottling":                         newCountFieldInfo(" Number of 429 and 503 errors in GET and HEAD requests to S3 storage."),
			"S3ReadRequestsRedirects":                          newCountFieldInfo(" Number of redirects in GET and HEAD requests to S3 storage."),
			"S3WriteMicroseconds":                              newCountFieldInfo(" Time of POST, DELETE, PUT and PATCH requests to S3 storage."),
			"S3WriteBytes":                                     newCountFieldInfo(" Write bytes (outgoing) in POST, DELETE, PUT and PATCH requests to S3 storage."),
			"S3WriteRequestsCount":                             newCountFieldInfo(" Number of POST, DELETE, PUT and PATCH requests to S3 storage."),
			"S3WriteRequestsErrors":                            newCountFieldInfo(" Number of non-throttling errors in POST, DELETE, PUT and PATCH requests to S3 storage."),
			"S3WriteRequestsThrottling":                        newCountFieldInfo(" Number of 429 and 503 errors in POST, DELETE, PUT and PATCH requests to S3 storage."),
			"S3WriteRequestsRedirects":                         newCountFieldInfo(" Number of redirects in POST, DELETE, PUT and PATCH requests to S3 storage."),
			"QueryMemoryLimitExceeded":                         newCountFieldInfo(" Number of times when memory limit exceeded for query."),
			"RemoteFSReadMicroseconds":                         newCountFieldInfo(" Time of reading from remote filesystem."),
			"RemoteFSReadBytes":                                newCountFieldInfo(" Read bytes from remote filesystem."),
			"RemoteFSSeeks":                                    newCountFieldInfo(" Total number of seeks for async buffer"),
			"RemoteFSPrefetches":                               newCountFieldInfo(" Number of prefetches made with asynchronous reading from remote filesystem"),
			"RemoteFSCancelledPrefetches":                      newCountFieldInfo(" Number of canceled prefecthes (because of seek)"),
			"RemoteFSUnusedPrefetches":                         newCountFieldInfo(" Number of prefetches pending at buffer destruction"),
			"RemoteFSPrefetchedReads":                          newCountFieldInfo(" Number of reads from prefecthed buffer"),
			"RemoteFSUnprefetchedReads":                        newCountFieldInfo(" Number of reads from unprefetched buffer"),
			"RemoteFSBuffers":                                  newCountFieldInfo(" Number of buffers created for asynchronous reading from remote filesystem"),
			"SleepFunctionCalls":                               newCountFieldInfo(" Number of times a sleep function (sleep, sleepEachRow) has been called."),
			"SleepFunctionMicroseconds":                        newCountFieldInfo(" Time spent sleeping due to a sleep function call."),
			"ThreadPoolReaderPageCacheHit":                     newCountFieldInfo(" Number of times the read inside ThreadPoolReader was done from page cache."),
			"ThreadPoolReaderPageCacheHitBytes":                newCountFieldInfo(" Number of bytes read inside ThreadPoolReader when it was done from page cache."),
			"ThreadPoolReaderPageCacheHitElapsedMicroseconds":  newCountFieldInfo(" Time spent reading data from page cache in ThreadPoolReader."),
			"ThreadPoolReaderPageCacheMiss":                    newCountFieldInfo(" Number of times the read inside ThreadPoolReader was not done from page cache and was hand off to thread pool."),
			"ThreadPoolReaderPageCacheMissBytes":               newCountFieldInfo(" Number of bytes read inside ThreadPoolReader when read was not done from page cache and was hand off to thread pool."),
			"ThreadPoolReaderPageCacheMissElapsedMicroseconds": newCountFieldInfo(" Time spent reading data inside the asynchronous job in ThreadPoolReader - when read was not done from page cache."),
			"AsynchronousReadWaitMicroseconds":                 newCountFieldInfo(" Time spent in waiting for asynchronous reads."),
			"ReplicatedPartMutations":                          newCountFieldInfo(defaultDesc),
			"ReplicatedPartChecks":                             newCountFieldInfo(defaultDesc),
			"ReplicatedPartChecksFailed":                       newCountFieldInfo(defaultDesc),
			"ObsoleteReplicatedParts":                          newCountFieldInfo(defaultDesc),
			"ZooKeeperInit":                                    newCountFieldInfo(defaultDesc),
			"ZooKeeperTransactions":                            newCountFieldInfo(defaultDesc),
			"ZooKeeperList":                                    newCountFieldInfo(defaultDesc),
			"ZooKeeperCreate":                                  newCountFieldInfo(defaultDesc),
			"ZooKeeperRemove":                                  newCountFieldInfo(defaultDesc),
			"ZooKeeperExists":                                  newCountFieldInfo(defaultDesc),
			"ZooKeeperGet":                                     newCountFieldInfo(defaultDesc),
			"ZooKeeperSet":                                     newCountFieldInfo(defaultDesc),
			"ZooKeeperMulti":                                   newCountFieldInfo(defaultDesc),
			"ZooKeeperCheck":                                   newCountFieldInfo(defaultDesc),
			"ZooKeeperClose":                                   newCountFieldInfo(defaultDesc),
			"ZooKeeperWatchResponse":                           newCountFieldInfo(defaultDesc),
			"ZooKeeperUserExceptions":                          newCountFieldInfo(defaultDesc),
			"ZooKeeperHardwareExceptions":                      newCountFieldInfo(defaultDesc),
			"ZooKeeperOtherExceptions":                         newCountFieldInfo(defaultDesc),
			"ZooKeeperWaitMicroseconds":                        newCountFieldInfo(defaultDesc),
			"ZooKeeperBytesSent":                               newCountFieldInfo(defaultDesc),
			"ZooKeeperBytesReceived":                           newCountFieldInfo(defaultDesc),
			"ExternalSortWritePart":                            newCountFieldInfo(defaultDesc),
			"ExternalSortMerge":                                newCountFieldInfo(defaultDesc),
			"ExternalAggregationWritePart":                     newCountFieldInfo(defaultDesc),
			"ExternalAggregationMerge":                         newCountFieldInfo(defaultDesc),
			"ExternalAggregationCompressedBytes":               newCountFieldInfo(defaultDesc),
			"ExternalAggregationUncompressedBytes":             newCountFieldInfo(defaultDesc),
			"DistributedConnectionMissingTable":                newCountFieldInfo(defaultDesc),
			"DistributedConnectionStaleReplica":                newCountFieldInfo(defaultDesc),
			"IOBufferAllocs":                                   newCountFieldInfo(defaultDesc),
			"IOBufferAllocBytes":                               newCountFieldInfo(defaultDesc),
			"ArenaAllocChunks":                                 newCountFieldInfo(defaultDesc),
			"ArenaAllocBytes":                                  newCountFieldInfo(defaultDesc),
			"FunctionExecute":                                  newCountFieldInfo(defaultDesc),
			"TableFunctionExecute":                             newCountFieldInfo(defaultDesc),
			"MarkCacheHits":                                    newCountFieldInfo(defaultDesc),
			"MarkCacheMisses":                                  newCountFieldInfo(defaultDesc),
			"CreatedReadBufferOrdinary":                        newCountFieldInfo(defaultDesc),
			"CreatedReadBufferDirectIO":                        newCountFieldInfo(defaultDesc),
			"CreatedReadBufferDirectIOFailed":                  newCountFieldInfo(defaultDesc),
			"CreatedReadBufferMMap":                            newCountFieldInfo(defaultDesc),
			"CreatedReadBufferMMapFailed":                      newCountFieldInfo(defaultDesc),
			"StorageBufferFlush":                               newCountFieldInfo(defaultDesc),
			"StorageBufferErrorOnFlush":                        newCountFieldInfo(defaultDesc),
			"StorageBufferPassedAllMinThresholds":              newCountFieldInfo(defaultDesc),
			"StorageBufferPassedTimeMaxThreshold":              newCountFieldInfo(defaultDesc),
			"StorageBufferPassedRowsMaxThreshold":              newCountFieldInfo(defaultDesc),
			"StorageBufferPassedBytesMaxThreshold":             newCountFieldInfo(defaultDesc),
			"StorageBufferPassedTimeFlushThreshold":            newCountFieldInfo(defaultDesc),
			"StorageBufferPassedRowsFlushThreshold":            newCountFieldInfo(defaultDesc),
			"StorageBufferPassedBytesFlushThreshold":           newCountFieldInfo(defaultDesc),
			"DictCacheKeysRequested":                           newCountFieldInfo(defaultDesc),
			"DictCacheKeysRequestedMiss":                       newCountFieldInfo(defaultDesc),
			"DictCacheKeysRequestedFound":                      newCountFieldInfo(defaultDesc),
			"DictCacheKeysExpired":                             newCountFieldInfo(defaultDesc),
			"DictCacheKeysNotFound":                            newCountFieldInfo(defaultDesc),
			"DictCacheKeysHit":                                 newCountFieldInfo(defaultDesc),
			"DictCacheRequestTimeNs":                           newCountFieldInfo(defaultDesc),
			"DictCacheRequests":                                newCountFieldInfo(defaultDesc),
			"DictCacheLockWriteNs":                             newCountFieldInfo(defaultDesc),
			"DictCacheLockReadNs":                              newCountFieldInfo(defaultDesc),
			"DistributedSyncInsertionTimeoutExceeded":          newCountFieldInfo(defaultDesc),
			"DataAfterMergeDiffersFromReplica":                 newCountFieldInfo(defaultDesc),
			"DataAfterMutationDiffersFromReplica":              newCountFieldInfo(defaultDesc),
			"PolygonsAddedToPool":                              newCountFieldInfo(defaultDesc),
			"PolygonsInPoolAllocatedBytes":                     newCountFieldInfo(defaultDesc),
			"RWLockAcquiredReadLocks":                          newCountFieldInfo(defaultDesc),
			"RWLockAcquiredWriteLocks":                         newCountFieldInfo(defaultDesc),
			"RWLockReadersWaitMilliseconds":                    newCountFieldInfo(defaultDesc),
			"RWLockWritersWaitMilliseconds":                    newCountFieldInfo(defaultDesc),
			"SoftPageFaults":                                   newCountFieldInfo(defaultDesc),
			"HardPageFaults":                                   newCountFieldInfo(defaultDesc),
			"VoluntaryContextSwitches":                         newCountFieldInfo(defaultDesc),
			"InvoluntaryContextSwitches":                       newCountFieldInfo(defaultDesc),
		},
		Tags: map[string]interface{}{
			"host": inputs.NewTagInfo("host name"),
		},
	}
}

//nolint:lll
func (m *StatusInfoMeasurement) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Name: metricsStatusInfo,
		Type: TypeMetric,
		Fields: map[string]interface{}{
			"DictionaryStatus": newGaugeFieldInfo(" Dictionary Status."),
		},
		Tags: map[string]interface{}{
			"host": inputs.NewTagInfo("host name"),
		},
	}
}

func newCountFieldInfo(desc string) *inputs.FieldInfo {
	return &inputs.FieldInfo{
		DataType: inputs.Int,
		Type:     inputs.Count,
		Unit:     inputs.NCount,
		Desc:     desc,
	}
}

//nolint:unparam
func newGaugeFieldInfo(desc string) *inputs.FieldInfo {
	return &inputs.FieldInfo{
		DataType: inputs.Int,
		Type:     inputs.Gauge,
		Unit:     inputs.NCount,
		Desc:     desc,
	}
}
