// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cachedata.proto

package dataway

import (
	bytes "bytes"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HTTPHeader struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *HTTPHeader) Reset()      { *m = HTTPHeader{} }
func (*HTTPHeader) ProtoMessage() {}
func (*HTTPHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0dd4f457c7a1df1, []int{0}
}
func (m *HTTPHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HTTPHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HTTPHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HTTPHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPHeader.Merge(m, src)
}
func (m *HTTPHeader) XXX_Size() int {
	return m.Size()
}
func (m *HTTPHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPHeader.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPHeader proto.InternalMessageInfo

func (m *HTTPHeader) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HTTPHeader) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// fail-cache proto message.
// NOTE: do not change field's number if you need to add more.
type CacheData struct {
	Payload     []byte        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers     []*HTTPHeader `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`
	DynURL      string        `protobuf:"bytes,7,opt,name=dynURL,proto3" json:"dynURL,omitempty"`
	Category    int32         `protobuf:"varint,1,opt,name=category,proto3" json:"category,omitempty"`
	PayloadType int32         `protobuf:"varint,2,opt,name=payloadType,proto3" json:"payloadType,omitempty"`
	Pts         int32         `protobuf:"varint,4,opt,name=pts,proto3" json:"pts,omitempty"`
	RawLen      int32         `protobuf:"varint,5,opt,name=rawLen,proto3" json:"rawLen,omitempty"`
	PkgTime     uint32        `protobuf:"varint,8,opt,name=pkgTime,proto3" json:"pkgTime,omitempty"`
}

func (m *CacheData) Reset()      { *m = CacheData{} }
func (*CacheData) ProtoMessage() {}
func (*CacheData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0dd4f457c7a1df1, []int{1}
}
func (m *CacheData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CacheData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CacheData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CacheData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheData.Merge(m, src)
}
func (m *CacheData) XXX_Size() int {
	return m.Size()
}
func (m *CacheData) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheData.DiscardUnknown(m)
}

var xxx_messageInfo_CacheData proto.InternalMessageInfo

func (m *CacheData) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CacheData) GetHeaders() []*HTTPHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *CacheData) GetDynURL() string {
	if m != nil {
		return m.DynURL
	}
	return ""
}

func (m *CacheData) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *CacheData) GetPayloadType() int32 {
	if m != nil {
		return m.PayloadType
	}
	return 0
}

func (m *CacheData) GetPts() int32 {
	if m != nil {
		return m.Pts
	}
	return 0
}

func (m *CacheData) GetRawLen() int32 {
	if m != nil {
		return m.RawLen
	}
	return 0
}

func (m *CacheData) GetPkgTime() uint32 {
	if m != nil {
		return m.PkgTime
	}
	return 0
}

func init() {
	proto.RegisterType((*HTTPHeader)(nil), "dataway.HTTPHeader")
	proto.RegisterType((*CacheData)(nil), "dataway.CacheData")
}

func init() { proto.RegisterFile("cachedata.proto", fileDescriptor_b0dd4f457c7a1df1) }

var fileDescriptor_b0dd4f457c7a1df1 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4e, 0xf3, 0x40,
	0x10, 0x85, 0x3d, 0x7f, 0x7e, 0xc7, 0xc9, 0x04, 0x04, 0x5a, 0x10, 0x5a, 0x51, 0x8c, 0xac, 0x54,
	0x6e, 0x30, 0x12, 0xd0, 0xd1, 0x20, 0xa0, 0x48, 0x91, 0x02, 0xad, 0x4c, 0x43, 0x37, 0xc4, 0xab,
	0x04, 0x25, 0xc4, 0x96, 0x63, 0x88, 0xdc, 0x71, 0x04, 0x8e, 0xc1, 0x51, 0x28, 0x53, 0xa6, 0x24,
	0x9b, 0x86, 0x0a, 0xe5, 0x08, 0xc8, 0x1b, 0x07, 0xe8, 0xde, 0xf7, 0x76, 0x35, 0x6f, 0xde, 0xe0,
	0x4e, 0x8f, 0x7b, 0x03, 0x1d, 0x73, 0xce, 0x61, 0x9a, 0x25, 0x79, 0x22, 0xbc, 0x52, 0x4f, 0xb9,
	0x68, 0x9f, 0x21, 0x76, 0xa2, 0xe8, 0xa6, 0xa3, 0x39, 0xd6, 0x99, 0xd8, 0xc5, 0xda, 0x50, 0x17,
	0x12, 0x7c, 0x08, 0x9a, 0xaa, 0x94, 0x62, 0x1f, 0xdd, 0x67, 0x1e, 0x3d, 0x69, 0xf9, 0xcf, 0x7a,
	0x6b, 0x68, 0x7f, 0x01, 0x36, 0xaf, 0xca, 0x91, 0xd7, 0x9c, 0xb3, 0x90, 0xe8, 0xa5, 0x5c, 0x8c,
	0x12, 0x8e, 0x65, 0xcd, 0x87, 0x60, 0x4b, 0x6d, 0x50, 0x1c, 0xa1, 0x37, 0xb0, 0x93, 0x27, 0xb2,
	0xee, 0xd7, 0x82, 0xd6, 0xc9, 0x5e, 0x58, 0x05, 0x87, 0xbf, 0xa9, 0x6a, 0xf3, 0x47, 0x1c, 0x60,
	0x3d, 0x2e, 0xc6, 0xb7, 0xaa, 0x2b, 0x3d, 0x9b, 0x56, 0x91, 0x38, 0xc4, 0x46, 0x8f, 0x73, 0xdd,
	0x4f, 0xb2, 0xf5, 0x6e, 0xae, 0xfa, 0x61, 0xe1, 0x63, 0xab, 0x4a, 0x8b, 0x8a, 0x74, 0xbd, 0xa6,
	0xab, 0xfe, 0x5a, 0x65, 0xa9, 0x34, 0x9f, 0xc8, 0xff, 0xf6, 0xa5, 0x94, 0x65, 0x4e, 0xc6, 0xd3,
	0xae, 0x1e, 0x4b, 0xd7, 0x9a, 0x15, 0xd9, 0x22, 0xc3, 0x7e, 0xf4, 0xf0, 0xa8, 0x65, 0xc3, 0x87,
	0x60, 0x5b, 0x6d, 0xf0, 0xf2, 0x62, 0xb6, 0x20, 0x67, 0xbe, 0x20, 0x67, 0xb5, 0x20, 0x78, 0x31,
	0x04, 0x6f, 0x86, 0xe0, 0xdd, 0x10, 0xcc, 0x0c, 0xc1, 0x87, 0x21, 0xf8, 0x34, 0xe4, 0xac, 0x0c,
	0xc1, 0xeb, 0x92, 0x9c, 0xd9, 0x92, 0x9c, 0xf9, 0x92, 0x9c, 0x3b, 0x0c, 0x8f, 0xcf, 0xab, 0xbe,
	0xf7, 0x75, 0x7b, 0xf8, 0xd3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x30, 0x39, 0xce, 0x8b,
	0x01, 0x00, 0x00,
}

func (this *HTTPHeader) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HTTPHeader)
	if !ok {
		that2, ok := that.(HTTPHeader)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Key != that1.Key {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	return true
}
func (this *CacheData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CacheData)
	if !ok {
		that2, ok := that.(CacheData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Payload, that1.Payload) {
		return false
	}
	if len(this.Headers) != len(that1.Headers) {
		return false
	}
	for i := range this.Headers {
		if !this.Headers[i].Equal(that1.Headers[i]) {
			return false
		}
	}
	if this.DynURL != that1.DynURL {
		return false
	}
	if this.Category != that1.Category {
		return false
	}
	if this.PayloadType != that1.PayloadType {
		return false
	}
	if this.Pts != that1.Pts {
		return false
	}
	if this.RawLen != that1.RawLen {
		return false
	}
	if this.PkgTime != that1.PkgTime {
		return false
	}
	return true
}
func (this *HTTPHeader) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&dataway.HTTPHeader{")
	s = append(s, "Key: "+fmt.Sprintf("%#v", this.Key)+",\n")
	s = append(s, "Value: "+fmt.Sprintf("%#v", this.Value)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CacheData) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&dataway.CacheData{")
	s = append(s, "Payload: "+fmt.Sprintf("%#v", this.Payload)+",\n")
	if this.Headers != nil {
		s = append(s, "Headers: "+fmt.Sprintf("%#v", this.Headers)+",\n")
	}
	s = append(s, "DynURL: "+fmt.Sprintf("%#v", this.DynURL)+",\n")
	s = append(s, "Category: "+fmt.Sprintf("%#v", this.Category)+",\n")
	s = append(s, "PayloadType: "+fmt.Sprintf("%#v", this.PayloadType)+",\n")
	s = append(s, "Pts: "+fmt.Sprintf("%#v", this.Pts)+",\n")
	s = append(s, "RawLen: "+fmt.Sprintf("%#v", this.RawLen)+",\n")
	s = append(s, "PkgTime: "+fmt.Sprintf("%#v", this.PkgTime)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringCachedata(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *HTTPHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HTTPHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HTTPHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintCachedata(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintCachedata(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CacheData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CacheData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CacheData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PkgTime != 0 {
		i = encodeVarintCachedata(dAtA, i, uint64(m.PkgTime))
		i--
		dAtA[i] = 0x40
	}
	if len(m.DynURL) > 0 {
		i -= len(m.DynURL)
		copy(dAtA[i:], m.DynURL)
		i = encodeVarintCachedata(dAtA, i, uint64(len(m.DynURL)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Headers) > 0 {
		for iNdEx := len(m.Headers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Headers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCachedata(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.RawLen != 0 {
		i = encodeVarintCachedata(dAtA, i, uint64(m.RawLen))
		i--
		dAtA[i] = 0x28
	}
	if m.Pts != 0 {
		i = encodeVarintCachedata(dAtA, i, uint64(m.Pts))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintCachedata(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PayloadType != 0 {
		i = encodeVarintCachedata(dAtA, i, uint64(m.PayloadType))
		i--
		dAtA[i] = 0x10
	}
	if m.Category != 0 {
		i = encodeVarintCachedata(dAtA, i, uint64(m.Category))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCachedata(dAtA []byte, offset int, v uint64) int {
	offset -= sovCachedata(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HTTPHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovCachedata(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovCachedata(uint64(l))
	}
	return n
}

func (m *CacheData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Category != 0 {
		n += 1 + sovCachedata(uint64(m.Category))
	}
	if m.PayloadType != 0 {
		n += 1 + sovCachedata(uint64(m.PayloadType))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovCachedata(uint64(l))
	}
	if m.Pts != 0 {
		n += 1 + sovCachedata(uint64(m.Pts))
	}
	if m.RawLen != 0 {
		n += 1 + sovCachedata(uint64(m.RawLen))
	}
	if len(m.Headers) > 0 {
		for _, e := range m.Headers {
			l = e.Size()
			n += 1 + l + sovCachedata(uint64(l))
		}
	}
	l = len(m.DynURL)
	if l > 0 {
		n += 1 + l + sovCachedata(uint64(l))
	}
	if m.PkgTime != 0 {
		n += 1 + sovCachedata(uint64(m.PkgTime))
	}
	return n
}

func sovCachedata(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCachedata(x uint64) (n int) {
	return sovCachedata(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *HTTPHeader) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&HTTPHeader{`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`Value:` + fmt.Sprintf("%v", this.Value) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CacheData) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForHeaders := "[]*HTTPHeader{"
	for _, f := range this.Headers {
		repeatedStringForHeaders += strings.Replace(f.String(), "HTTPHeader", "HTTPHeader", 1) + ","
	}
	repeatedStringForHeaders += "}"
	s := strings.Join([]string{`&CacheData{`,
		`Category:` + fmt.Sprintf("%v", this.Category) + `,`,
		`PayloadType:` + fmt.Sprintf("%v", this.PayloadType) + `,`,
		`Payload:` + fmt.Sprintf("%v", this.Payload) + `,`,
		`Pts:` + fmt.Sprintf("%v", this.Pts) + `,`,
		`RawLen:` + fmt.Sprintf("%v", this.RawLen) + `,`,
		`Headers:` + repeatedStringForHeaders + `,`,
		`DynURL:` + fmt.Sprintf("%v", this.DynURL) + `,`,
		`PkgTime:` + fmt.Sprintf("%v", this.PkgTime) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringCachedata(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *HTTPHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCachedata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HTTPHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HTTPHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCachedata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCachedata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCachedata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCachedata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCachedata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCachedata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CacheData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCachedata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CacheData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CacheData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			m.Category = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Category |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayloadType", wireType)
			}
			m.PayloadType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PayloadType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCachedata
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCachedata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pts", wireType)
			}
			m.Pts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pts |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawLen", wireType)
			}
			m.RawLen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RawLen |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Headers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCachedata
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCachedata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Headers = append(m.Headers, &HTTPHeader{})
			if err := m.Headers[len(m.Headers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DynURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCachedata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCachedata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DynURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PkgTime", wireType)
			}
			m.PkgTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PkgTime |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCachedata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCachedata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCachedata(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCachedata
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCachedata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCachedata
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCachedata
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCachedata
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCachedata        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCachedata          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCachedata = fmt.Errorf("proto: unexpected end of group")
)
