FROM registry.jiagouyun.com/middlewares/uniontechos-server-zy-root:v2.0 AS base
ARG TARGETARCH
ARG APP_DIR="/usr/local/dca/"
ARG DIST_DIR

RUN mkdir -p ${APP_DIR}

WORKDIR ${APP_DIR}

COPY ${DIST_DIR}/dca-linux-${TARGETARCH}/ .
COPY ${DIST_DIR}/dca-web ${APP_DIR}public/
CMD ["/usr/local/dca/dca"]
EXPOSE 80
