// Unless explicitly stated otherwise all files in this repository are licensed
// under the MIT License.
// This product includes software developed at Guance Cloud (https://www.guance.com/).
// Copyright 2021-present Guance, Inc.

//nolint:lll,goconst,funlen // Measurement metadata contains intentionally long repeated literals.
package ebpf

import (
	"github.com/GuanceCloud/cliutils/point"
	"gitlab.jiagouyun.com/cloudcare-tools/datakit/internal/plugins/inputs"
)

type ConnStatsM struct{}

//nolint:lll
func (m *ConnStatsM) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Name:   "netflow",
		Cat:    point.Network,
		Desc:   "Aggregated network connection metrics generated by the eBPF network collector for TCP/UDP traffic over each collection interval.",
		DescZh: "eBPF 网络采集器按采集周期聚合生成的 TCP/UDP 网络连接指标。",
		Tags: map[string]interface{}{
			"host":           &inputs.TagInfo{Desc: "System hostname"},
			"client_ip":      &inputs.TagInfo{Desc: "Client IP address"},
			"client_port":    &inputs.TagInfo{Desc: "Client port"},
			"client_ip_type": &inputs.TagInfo{Desc: "Client IP type. (other/private/multicast)"},
			"server_ip":      &inputs.TagInfo{Desc: "Server IP"},
			"server_port":    &inputs.TagInfo{Desc: "Server port"},
			"server_ip_type": &inputs.TagInfo{Desc: "Server IP type. (other/private/multicast)"},
			"server_domain":  &inputs.TagInfo{Desc: "Server domain"},

			"client_k8s_pod_name":        &inputs.TagInfo{Desc: "Client K8s pod name"},
			"client_k8s_deployment_name": &inputs.TagInfo{Desc: "Client K8s deployment name"},
			"client_k8s_service_name":    &inputs.TagInfo{Desc: "Client K8s service name"},
			"client_k8s_namespace":       &inputs.TagInfo{Desc: "Client K8s namespace"},
			"server_k8s_pod_name":        &inputs.TagInfo{Desc: "Server K8s pod name"},
			"server_k8s_deployment_name": &inputs.TagInfo{Desc: "Server K8s deployment name"},
			"server_k8s_service_name":    &inputs.TagInfo{Desc: "Server K8s service name"},
			"server_k8s_namespace":       &inputs.TagInfo{Desc: "Server K8s namespace"},

			"dst_ip":     &inputs.TagInfo{Desc: "Destination IP address"},
			"dst_domain": &inputs.TagInfo{Desc: "Destination domain"},
			"dst_port":   &inputs.TagInfo{Desc: "Destination port"},
			"dst_nat_ip": &inputs.TagInfo{Desc: "For data containing the `outgoing` tag, " +
				"this value is the ip after the DNAT operation"},
			"dst_nat_port": &inputs.TagInfo{Desc: "For data containing the `outgoing` tag, " +
				"this value is the port after the DNAT operation"},
			"dst_ip_type":             &inputs.TagInfo{Desc: "Destination IP type. (other/private/multicast)"},
			"src_ip":                  &inputs.TagInfo{Desc: "Source IP"},
			"src_port":                &inputs.TagInfo{Desc: "Source port"},
			"src_ip_type":             &inputs.TagInfo{Desc: "Source IP type. (other/private/multicast)"},
			"src_k8s_pod_name":        &inputs.TagInfo{Desc: "Source K8s pod name"},
			"src_k8s_deployment_name": &inputs.TagInfo{Desc: "Source K8s deployment name"},
			"src_k8s_service_name":    &inputs.TagInfo{Desc: "Source K8s service name"},
			"src_k8s_namespace":       &inputs.TagInfo{Desc: "Source K8s namespace"},
			"dst_k8s_pod_name":        &inputs.TagInfo{Desc: "Destination K8s pod name"},
			"dst_k8s_deployment_name": &inputs.TagInfo{Desc: "Destination K8s deployment name"},
			"dst_k8s_service_name":    &inputs.TagInfo{Desc: "Destination K8s service name"},
			"dst_k8s_namespace":       &inputs.TagInfo{Desc: "Destination K8s namespace"},
			"pid":                     &inputs.TagInfo{Desc: "Process identification number"},
			"process_name":            &inputs.TagInfo{Desc: "Process name"},
			"transport":               &inputs.TagInfo{Desc: "Transport layer protocol. (udp/tcp)"},
			"family":                  &inputs.TagInfo{Desc: "Network layer protocol. (IPv4/IPv6)"},
			"direction":               &inputs.TagInfo{Desc: "Use the source (src_ip:src_port) as a frame of reference to identify the connection initiator. (incoming/outgoing)"},
			"source":                  &inputs.TagInfo{Desc: "Fixed value: `netflow`."},
			"sub_source":              &inputs.TagInfo{Desc: "Some specific connection classifications, such as the sub_source value for Kubernetes network traffic is K8s"},
		},
		Fields: map[string]interface{}{
			"bytes_read":           &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeByte, Desc: "The number of bytes read"},
			"bytes_written":        &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeByte, Desc: "The number of bytes written"},
			"packets_read":         &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of packets read"},
			"packets_written":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of packets written"},
			"retransmits":          &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of retransmissions"},
			"rtt":                  &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.DurationUS, Desc: "TCP Latency"},
			"rtt_var":              &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.DurationUS, Desc: "TCP Jitter"},
			"tcp_closed":           &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of TCP connection closed"},
			"tcp_established":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of TCP connection established"},
			"tcp_connect_attempts": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of TCP connection attempts"},
			"tcp_connect_failures": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of TCP connection failures"},
			"tcp_close_wait":       &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of TCP_CLOSE_WAIT state transitions"},
			"tcp_last_ack":         &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of TCP_LAST_ACK state transitions"},
			"tcp_time_wait":        &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of TCP_TIME_WAIT state transitions"},
		},
	}
}

type HTTPFlowM struct{}

//nolint:lll
func (m *HTTPFlowM) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Name:   "httpflow",
		Cat:    point.Network,
		Desc:   "Aggregated HTTP request metrics generated by the eBPF network collector for each collection interval.",
		DescZh: "eBPF 网络采集器按采集周期聚合生成的 HTTP 请求指标。",
		Tags: map[string]interface{}{
			"host": &inputs.TagInfo{Desc: "System hostname"},

			"client_ip":      &inputs.TagInfo{Desc: "Client IP address"},
			"client_port":    &inputs.TagInfo{Desc: "Client port"},
			"client_ip_type": &inputs.TagInfo{Desc: "Client IP type. (other/private/multicast)"},
			"server_ip":      &inputs.TagInfo{Desc: "Server IP"},
			"server_port":    &inputs.TagInfo{Desc: "Server port"},
			"server_ip_type": &inputs.TagInfo{Desc: "Server IP type. (other/private/multicast)"},
			"server_domain":  &inputs.TagInfo{Desc: "Server domain"},

			"client_k8s_pod_name":        &inputs.TagInfo{Desc: "Client K8s pod name"},
			"client_k8s_deployment_name": &inputs.TagInfo{Desc: "Client K8s deployment name"},
			"client_k8s_service_name":    &inputs.TagInfo{Desc: "Client K8s service name"},
			"client_k8s_namespace":       &inputs.TagInfo{Desc: "Client K8s namespace"},
			"server_k8s_pod_name":        &inputs.TagInfo{Desc: "Server K8s pod name"},
			"server_k8s_deployment_name": &inputs.TagInfo{Desc: "Server K8s deployment name"},
			"server_k8s_service_name":    &inputs.TagInfo{Desc: "Server K8s service name"},
			"server_k8s_namespace":       &inputs.TagInfo{Desc: "Server K8s namespace"},

			"dst_ip":      &inputs.TagInfo{Desc: "Destination IP address"},
			"dst_domain":  &inputs.TagInfo{Desc: "Destination domain"},
			"dst_port":    &inputs.TagInfo{Desc: "Destination port"},
			"dst_ip_type": &inputs.TagInfo{Desc: "Destination IP type. (other/private/multicast)"},
			"dst_nat_ip": &inputs.TagInfo{Desc: "For data containing the `outgoing` tag, " +
				"this value is the ip after the DNAT operation"},
			"dst_nat_port": &inputs.TagInfo{Desc: "For data containing the `outgoing` tag, " +
				"this value is the port after the DNAT operation"},
			"src_ip":                  &inputs.TagInfo{Desc: "Source IP"},
			"src_port":                &inputs.TagInfo{Desc: "Source port"},
			"src_ip_type":             &inputs.TagInfo{Desc: "Source IP type. (other/private/multicast)"},
			"src_k8s_pod_name":        &inputs.TagInfo{Desc: "Source K8s pod name"},
			"src_k8s_deployment_name": &inputs.TagInfo{Desc: "Source K8s deployment name"},
			"src_k8s_service_name":    &inputs.TagInfo{Desc: "Source K8s service name"},
			"src_k8s_namespace":       &inputs.TagInfo{Desc: "Source K8s namespace"},
			"dst_k8s_pod_name":        &inputs.TagInfo{Desc: "Destination K8s pod name"},
			"dst_k8s_deployment_name": &inputs.TagInfo{Desc: "Destination K8s deployment name"},
			"dst_k8s_service_name":    &inputs.TagInfo{Desc: "Destination K8s service name"},
			"dst_k8s_namespace":       &inputs.TagInfo{Desc: "Destination K8s namespace"},
			"pid":                     &inputs.TagInfo{Desc: "Process identification number"},
			"process_name":            &inputs.TagInfo{Desc: "Process name"},
			"transport":               &inputs.TagInfo{Desc: "Transport layer protocol. (udp/tcp)"},
			"family":                  &inputs.TagInfo{Desc: "Network layer protocol. (IPv4/IPv6)"},
			"direction":               &inputs.TagInfo{Desc: "Use the source (src_ip:src_port) as a frame of reference to identify the connection initiator. (incoming/outgoing)"},
			"source":                  &inputs.TagInfo{Desc: "Fixed value: `httpflow`."},
			"sub_source":              &inputs.TagInfo{Desc: "Some specific connection classifications, such as the sub_source value for Kubernetes network traffic is K8s"},
		},
		Fields: map[string]interface{}{
			"truncated":     &inputs.FieldInfo{DataType: inputs.Bool, Type: inputs.Gauge, Unit: inputs.Bool, Desc: "The length of the request path has reached the upper limit of the number of bytes collected, and the request path may be truncated"},
			"path":          &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Request path"},
			"status_code":   &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NoUnit, Desc: "HTTP status code"},
			"method":        &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "GET/POST/..."},
			"latency":       &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.DurationNS, Desc: "TTFB"},
			"http_version":  &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "1.1 / 1.0 ..."},
			"count":         &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The total number of HTTP requests in a collection cycle"},
			"bytes_read":    &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeByte, Desc: "The number of bytes read"},
			"bytes_written": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeByte, Desc: "The number of bytes written"},
		},
	}
}

type DNSStatsM struct{}

//nolint:lll
func (m *DNSStatsM) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Name:   "dnsflow",
		Cat:    point.Network,
		Desc:   "Aggregated DNS request metrics generated by the eBPF network collector for each collection interval.",
		DescZh: "eBPF 网络采集器按采集周期聚合生成的 DNS 请求指标。",
		Tags: map[string]interface{}{
			"host":                    &inputs.TagInfo{Desc: "System hostname"},
			"dst_ip":                  &inputs.TagInfo{Desc: "Destination IP address"},
			"dst_domain":              &inputs.TagInfo{Desc: "Destination domain"},
			"dst_port":                &inputs.TagInfo{Desc: "Destination port"},
			"dst_ip_type":             &inputs.TagInfo{Desc: "Destination IP type. (other/private/multicast)"},
			"src_ip":                  &inputs.TagInfo{Desc: "Source IP"},
			"src_port":                &inputs.TagInfo{Desc: "Source port"},
			"src_ip_type":             &inputs.TagInfo{Desc: "Source IP type. (other/private/multicast)"},
			"src_k8s_pod_name":        &inputs.TagInfo{Desc: "Source K8s pod name"},
			"src_k8s_deployment_name": &inputs.TagInfo{Desc: "Source K8s deployment name"},
			"src_k8s_service_name":    &inputs.TagInfo{Desc: "Source K8s service name"},
			"src_k8s_namespace":       &inputs.TagInfo{Desc: "Source K8s namespace"},
			"dst_k8s_pod_name":        &inputs.TagInfo{Desc: "Destination K8s pod name"},
			"dst_k8s_deployment_name": &inputs.TagInfo{Desc: "Destination K8s deployment name"},
			"dst_k8s_service_name":    &inputs.TagInfo{Desc: "Destination K8s service name"},
			"dst_k8s_namespace":       &inputs.TagInfo{Desc: "Destination K8s namespace"},
			// "pid":                     inputs.TagInfo{Desc: "Process identification number"},
			// "process_name":            inputs.TagInfo{Desc: "Process name"},
			"transport":  &inputs.TagInfo{Desc: "Transport layer protocol. (udp/tcp)"},
			"family":     &inputs.TagInfo{Desc: "Network layer protocol. (IPv4/IPv6)"},
			"direction":  &inputs.TagInfo{Desc: "Use the source (src_ip:src_port) as a frame of reference to identify the connection initiator. (incoming/outgoing)"},
			"query_type": &inputs.TagInfo{Desc: "DNS query type. (A/AAAA/NS/...)"},
			"source":     &inputs.TagInfo{Desc: "Fixed value: `dnsflow`."},
			"sub_source": &inputs.TagInfo{Desc: "Some specific connection classifications, " +
				"such as the sub_source value for Kubernetes network traffic is K8s"},
		},
		Fields: map[string]interface{}{
			"rcode": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NoUnit, Desc: "DNS response code: 0 - `NoError`, 1 - `FormErr`, 2 - `ServFail`, " +
				"3 - NXDomain, 4 - NotImp, 5 - Refused, ...; A value of -1 means the request timed out"},

			"count":        &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of DNS requests in a collection cycle"},
			"latency":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.DurationNS, Desc: "Average response time for DNS requests"},
			"latency_max":  &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.DurationNS, Desc: "Maximum response time for DNS requests"},
			"query_domain": &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "The queried domain name from the DNS request"},
		},
	}
}

type BashM struct{}

//nolint:lll
func (m *BashM) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Name:   "bash",
		Cat:    point.Logging,
		Desc:   "Bash command execution records captured by the eBPF bash history plugin.",
		DescZh: "eBPF bash history 插件采集的 Bash 命令执行记录。",
		Tags: map[string]interface{}{
			"host": &inputs.TagInfo{Desc: "host name"},
		},
		Fields: map[string]interface{}{
			"pid":     &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Process identification number"},
			"user":    &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "The user who executes the bash command"},
			"cmd":     &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Command"},
			"message": &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "The bash execution record generated by the collector"},
		},
	}
}

type BPFL4Log struct{}

//nolint:lll
func (bpfl4 *BPFL4Log) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Cat:    point.Logging,
		Name:   "bpf_net_l4_log",
		Desc:   "Layer 4 network packet log records generated by the eBPF netlog plugin.",
		DescZh: "eBPF netlog 插件生成的四层网络包日志记录。",
		Tags: map[string]interface{}{
			"host":          &inputs.TagInfo{Desc: "Host name"},
			"client_ip":     &inputs.TagInfo{Desc: "The IP address of the client"},
			"client_port":   &inputs.TagInfo{Desc: "Client port"},
			"server_ip":     &inputs.TagInfo{Desc: "The IP address of the server"},
			"server_port":   &inputs.TagInfo{Desc: "Server port"},
			"conn_side":     &inputs.TagInfo{Desc: "The side of the connection: client/server/unknown"},
			"src_ip":        &inputs.TagInfo{Desc: "The IP address of the collected local network interface"},
			"src_port":      &inputs.TagInfo{Desc: "Local port"},
			"dst_ip":        &inputs.TagInfo{Desc: "The IP address of the foreign network interface"},
			"dst_port":      &inputs.TagInfo{Desc: "Foreign port"},
			"l4_proto":      &inputs.TagInfo{Desc: "Transport protocol"},
			"l7_proto":      &inputs.TagInfo{Desc: "Application protocol"},
			"nic_mac":       &inputs.TagInfo{Desc: "MAC address of the collected network interface"},
			"nic_name":      &inputs.TagInfo{Desc: "Name of the collected network interface"},
			"netns":         &inputs.TagInfo{Desc: "Network namespace, format: `NS(<device id>:<inode number>)`"},
			"vni_id":        &inputs.TagInfo{Desc: "Virtual Network Identifier"},
			"vxlan_packet":  &inputs.TagInfo{Desc: "Whether it is a VXLAN packet"},
			"inner_traceid": &inputs.TagInfo{Desc: "Correlate the layer 4 and layer 7 network log data of a TCP connection on the collected network interface"},
			"host_network":  &inputs.TagInfo{Desc: "Whether the network log data is collected on the host network"},
			"virtual_nic":   &inputs.TagInfo{Desc: "Whether the network log data is collected on the virtual network interface"},
			"direction":     &inputs.TagInfo{Desc: "Use the source (src_ip:src_port) as a frame of reference to identify the connection initiator. (incoming/outgoing)"},

			"k8s_namespace":      &inputs.TagInfo{Desc: "Kubernetes namespace"},
			"k8s_pod_name":       &inputs.TagInfo{Desc: "Kubernetes pod name"},
			"k8s_container_name": &inputs.TagInfo{Desc: "Kubernetes container name"},

			"sub_source":              &inputs.TagInfo{Desc: "Some specific connection classifications, such as the sub_source value for Kubernetes network traffic is K8s"},
			"src_k8s_pod_name":        &inputs.TagInfo{Desc: "Source K8s pod name"},
			"src_k8s_deployment_name": &inputs.TagInfo{Desc: "Source K8s deployment name"},
			"src_k8s_service_name":    &inputs.TagInfo{Desc: "Source K8s service name"},
			"src_k8s_namespace":       &inputs.TagInfo{Desc: "Source K8s namespace"},
			"dst_k8s_pod_name":        &inputs.TagInfo{Desc: "Destination K8s pod name"},
			"dst_k8s_deployment_name": &inputs.TagInfo{Desc: "Destination K8s deployment name"},
			"dst_k8s_service_name":    &inputs.TagInfo{Desc: "Destination K8s service name"},
			"dst_k8s_namespace":       &inputs.TagInfo{Desc: "Destination K8s namespace"},
		},
		Fields: map[string]interface{}{
			"chunk_id":        &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "A connection may be divided into several chunks for upload based on time interval or TCP segment number"},
			"tx_seq_min":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NoUnit, Desc: "The minimum value of the TCP sequence number of the data packet sent by the network interface, which is a 32-bit unsigned integer"},
			"tx_seq_max":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NoUnit, Desc: "The maximum value of the TCP sequence number of the data packet sent by the network interface, which is a 32-bit unsigned integer"},
			"rx_seq_min":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NoUnit, Desc: "The minimum value of the TCP sequence number of the data packet received by the network interface, which is a 32-bit unsigned integer"},
			"rx_seq_max":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NoUnit, Desc: "The maximum value of the TCP sequence number of the data packet received by the network interface, which is a 32-bit unsigned integer"},
			"tx_bytes":        &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeByte, Desc: "The number of bytes sent by the network interface"},
			"rx_bytes":        &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeByte, Desc: "The number of bytes received by the network interface"},
			"tx_packets":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of packets sent by the network interface"},
			"rx_packets":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of packets received by the network interface"},
			"tx_retrans":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of retransmitted packets sent by the network interface"},
			"rx_retrans":      &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of retransmitted packets received by the network interface"},
			"tcp_syn_retrans": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NCount, Desc: "The number of retransmitted SYN packets sent by the network interface"},
		},
	}
}

type BPFL7Log struct{}

//nolint:lll
func (bpfl7 *BPFL7Log) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Cat:    point.Logging,
		Name:   "bpf_net_l7_log",
		Desc:   "Layer 7 network request log records generated by the eBPF netlog plugin.",
		DescZh: "eBPF netlog 插件生成的七层网络请求日志记录。",
		Tags: map[string]interface{}{
			"host":          &inputs.TagInfo{Desc: "Host name"},
			"client_ip":     &inputs.TagInfo{Desc: "The IP address of the client"},
			"client_port":   &inputs.TagInfo{Desc: "Client port"},
			"server_ip":     &inputs.TagInfo{Desc: "The IP address of the server"},
			"server_port":   &inputs.TagInfo{Desc: "Server port"},
			"conn_side":     &inputs.TagInfo{Desc: "The side of the connection: client/server/unknown"},
			"src_ip":        &inputs.TagInfo{Desc: "The IP address of the collected local network interface"},
			"src_port":      &inputs.TagInfo{Desc: "Local port"},
			"dst_ip":        &inputs.TagInfo{Desc: "The IP address of the foreign network interface"},
			"dst_port":      &inputs.TagInfo{Desc: "Foreign port"},
			"l4_proto":      &inputs.TagInfo{Desc: "Transport protocol"},
			"l7_proto":      &inputs.TagInfo{Desc: "Application protocol"},
			"nic_mac":       &inputs.TagInfo{Desc: "MAC address of the collected network interface"},
			"nic_name":      &inputs.TagInfo{Desc: "Name of the collected network interface"},
			"netns":         &inputs.TagInfo{Desc: "Network namespace, format: `NS(<device id>:<inode number>)`"},
			"vni_id":        &inputs.TagInfo{Desc: "Virtual Network Identifier"},
			"vxlan_packet":  &inputs.TagInfo{Desc: "Whether it is a VXLAN packet"},
			"inner_traceid": &inputs.TagInfo{Desc: "Correlate the layer 4 and layer 7 network log data of a TCP connection on the collected network interface"},
			"host_network":  &inputs.TagInfo{Desc: "Whether the network log data is collected on the host network"},
			"virtual_nic":   &inputs.TagInfo{Desc: "Whether the network log data is collected on the virtual network interface"},
			"direction":     &inputs.TagInfo{Desc: "Use the source (src_ip:src_port) as a frame of reference to identify the connection initiator. (incoming/outgoing)"},

			"k8s_namespace":      &inputs.TagInfo{Desc: "Kubernetes namespace"},
			"k8s_pod_name":       &inputs.TagInfo{Desc: "Kubernetes pod name"},
			"k8s_container_name": &inputs.TagInfo{Desc: "Kubernetes container name"},

			"sub_source":              &inputs.TagInfo{Desc: "Some specific connection classifications, such as the sub_source value for Kubernetes network traffic is K8s"},
			"src_k8s_pod_name":        &inputs.TagInfo{Desc: "Source K8s pod name"},
			"src_k8s_deployment_name": &inputs.TagInfo{Desc: "Source K8s deployment name"},
			"src_k8s_service_name":    &inputs.TagInfo{Desc: "Source K8s service name"},
			"src_k8s_namespace":       &inputs.TagInfo{Desc: "Source K8s namespace"},
			"dst_k8s_pod_name":        &inputs.TagInfo{Desc: "Destination K8s pod name"},
			"dst_k8s_deployment_name": &inputs.TagInfo{Desc: "Destination K8s deployment name"},
			"dst_k8s_service_name":    &inputs.TagInfo{Desc: "Destination K8s service name"},
			"dst_k8s_namespace":       &inputs.TagInfo{Desc: "Destination K8s namespace"},

			"trace_id":  &inputs.TagInfo{Desc: "APM trace id"},
			"parent_id": &inputs.TagInfo{Desc: "The span id of the APM span corresponding to this network request"},

			"l7_traceid": &inputs.TagInfo{Desc: "Correlate the layer 7 network log data of a TCP connection on the all collected network interface"},
		},
		Fields: map[string]interface{}{
			"tx_seq": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NoUnit, Desc: "The TCP sequence number of the first request or response byte sent by the network interface"},
			"rx_seq": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NoUnit, Desc: "The TCP sequence number of the first request or response byte received by the network interface"},

			"http_status_code": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NoUnit, Desc: "HTTP status code"},
			"http_method":      &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "HTTP method"},
			"http_path":        &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "HTTP path"},
		},
	}
}

type EBPFTrace struct{}

func (bpftrace *EBPFTrace) Info() *inputs.MeasurementInfo {
	return &inputs.MeasurementInfo{
		Cat:    point.Tracing,
		Name:   "dketrace",
		Desc:   "eBPF trace spans generated from application network activity and forwarded for trace correlation.",
		DescZh: "基于应用网络活动生成并用于链路关联的 eBPF trace span。",
		Tags: map[string]any{
			"service":  &inputs.TagInfo{Desc: "Service name"},
			"host":     &inputs.TagInfo{Desc: "System hostname"},
			"dst_ip":   &inputs.TagInfo{Desc: "Destination IP address"},
			"dst_port": &inputs.TagInfo{Desc: "Destination port"},
			"src_ip":   &inputs.TagInfo{Desc: "Source IP"},
			"src_port": &inputs.TagInfo{Desc: "Source port"},
		},
		Fields: map[string]any{
			"span_id":   &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "APM span id, generated by the `ebpftrace` collector"},
			"trace_id":  &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "APM trace id, can choose between existing app trace id and ebpf generation,set by the `ebpftrace` collector"},
			"parent_id": &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "APM parent span id, set by the `ebpftrace` collector"},

			"ebpf_trace_id":  &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "eBPF trace id, generated by the `ebpftrace` collector"},
			"ebpf_parent_id": &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "eBPF parent span id, generated by the `ebpftrace` collector"},
			"app_trace_id":   &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Trace id carried by the application in the request"},
			"app_parent_id":  &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Parent span id carried by the application in the request"},

			"source_type": &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Source type, value is `ebpf`"},

			"pid":          &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Process identification number"},
			"process_name": &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Process name"},
			"thread_name":  &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Thread name"},

			"duration": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.DurationUS, Desc: "Duration"},
			"start":    &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.TimestampUS, Desc: "Start time"},

			"span_type": &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Span type"},

			"bytes_written": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeByte, Desc: "Bytes written"},
			"bytes_read":    &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.SizeByte, Desc: "Bytes read"},

			"http_route":       &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "HTTP route"},
			"http_method":      &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "HTTP method"},
			"http_status_code": &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "HTTP status code"},

			"grpc_status_code": &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "gRPC status code"},

			"mysql_status_code": &inputs.FieldInfo{DataType: inputs.Int, Type: inputs.Gauge, Unit: inputs.NoUnit, Desc: "MySQL request status code"},
			"mysql_err_msg":     &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "MySQL error message"},
			"resource_type":     &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Redis resource type"},
			"err_msg":           &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Redis error message"},
			"status_msg":        &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Redis status message"},
			"operation":         &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Operation"},
			"status":            &inputs.FieldInfo{DataType: inputs.String, Type: inputs.String, Unit: inputs.NoUnit, Desc: "Status"},
		},
	}
}
